const tours = {
  en: { home: "Home", tours: "Tours", title: "Explore Our Curated Tours", description: "Discover historical, cultural and luxury journeys created to reveal Africa's authentic beauty.", filters: "Filters", reset: "Reset All", categories: "Tour Categories", destination: "Destination", destinationSearch: "Search destination…", duration: "Duration", price: "Price Range", style: "Tour Style", availability: "Availability", rating: "Minimum Rating", searchDestination: "Search Destination", where: "Where in Africa?", category: "Tour Category", allCategories: "All Categories", travelDate: "Travel Date", selectDate: "Select date", anyDuration: "Any duration", clear: "Clear", search: "Search", found_one: "{{count}} tour found", found_other: "{{count}} tours found", apply: "Apply Filters", viewDetails: "View Details", bookNow: "Book Now", from: "From", perPerson: "per person", left: "{{count}} left", available: "Available", limited: "Limited", limitedSpots: "Limited Spots", bookingOpen: "Booking Open", all: "All", historical: "Historical", cultural: "Cultural", luxury: "Luxury", group: "Group", private: "Private", educational: "Educational", standard: "Standard", premium: "Premium", featured: "Featured", bestseller: "Bestseller", new: "New", any: "Any Duration", lowHigh: "Price: Low to High", highLow: "Price: High to Low", ratingHigh: "Rating: High to Low", popular: "Most Popular", newest: "Newest First" },
  de: { home: "Startseite", tours: "Reisen", title: "Unsere kuratierten Reisen entdecken", description: "Entdecken Sie historische, kulturelle und luxuriöse Reisen, die Afrikas authentische Schönheit zeigen.", filters: "Filter", reset: "Alle zurücksetzen", categories: "Reisekategorien", destination: "Reiseziel", destinationSearch: "Reiseziel suchen…", duration: "Dauer", price: "Preisspanne", style: "Reisestil", availability: "Verfügbarkeit", rating: "Mindestbewertung", searchDestination: "Reiseziel suchen", where: "Wohin in Afrika?", category: "Reisekategorie", allCategories: "Alle Kategorien", travelDate: "Reisedatum", selectDate: "Datum wählen", anyDuration: "Beliebige Dauer", clear: "Löschen", search: "Suchen", found_one: "{{count}} Reise gefunden", found_other: "{{count}} Reisen gefunden", apply: "Filter anwenden", viewDetails: "Details ansehen", bookNow: "Jetzt buchen", from: "Ab", perPerson: "pro Person", left: "{{count}} frei", available: "Verfügbar", limited: "Begrenzt", limitedSpots: "Wenige Plätze", bookingOpen: "Buchung geöffnet", all: "Alle", historical: "Historisch", cultural: "Kulturell", luxury: "Luxus", group: "Gruppe", private: "Privat", educational: "Bildung", standard: "Standard", premium: "Premium", featured: "Empfohlen", bestseller: "Bestseller", new: "Neu", any: "Beliebige Dauer", lowHigh: "Preis: aufsteigend", highLow: "Preis: absteigend", ratingHigh: "Bewertung: absteigend", popular: "Beliebteste", newest: "Neueste zuerst" },
  es: { home: "Inicio", tours: "Tours", title: "Explora nuestros tours seleccionados", description: "Descubre viajes históricos, culturales y de lujo creados para revelar la auténtica belleza de África.", filters: "Filtros", reset: "Restablecer", categories: "Categorías", destination: "Destino", destinationSearch: "Buscar destino…", duration: "Duración", price: "Rango de precios", style: "Estilo de tour", availability: "Disponibilidad", rating: "Valoración mínima", searchDestination: "Buscar destino", where: "¿Dónde en África?", category: "Categoría", allCategories: "Todas las categorías", travelDate: "Fecha de viaje", selectDate: "Seleccionar fecha", anyDuration: "Cualquier duración", clear: "Limpiar", search: "Buscar", found_one: "{{count}} tour encontrado", found_other: "{{count}} tours encontrados", apply: "Aplicar filtros", viewDetails: "Ver detalles", bookNow: "Reservar", from: "Desde", perPerson: "por persona", left: "{{count}} disponibles", available: "Disponible", limited: "Limitado", limitedSpots: "Plazas limitadas", bookingOpen: "Reservas abiertas", all: "Todos", historical: "Histórico", cultural: "Cultural", luxury: "Lujo", group: "Grupo", private: "Privado", educational: "Educativo", standard: "Estándar", premium: "Premium", featured: "Destacado", bestseller: "Más vendido", new: "Nuevo", any: "Cualquier duración", lowHigh: "Precio: menor a mayor", highLow: "Precio: mayor a menor", ratingHigh: "Valoración: mayor a menor", popular: "Más populares", newest: "Más recientes" },
  "zh-CN": { home: "首页", tours: "旅游行程", title: "探索我们的精选行程", description: "探索历史、文化与奢华旅程，领略非洲真实之美。", filters: "筛选", reset: "全部重置", categories: "行程类别", destination: "目的地", destinationSearch: "搜索目的地…", duration: "时长", price: "价格范围", style: "行程风格", availability: "可预订状态", rating: "最低评分", searchDestination: "搜索目的地", where: "非洲哪里？", category: "行程类别", allCategories: "全部类别", travelDate: "旅行日期", selectDate: "选择日期", anyDuration: "不限时长", clear: "清除", search: "搜索", found_other: "找到 {{count}} 个行程", apply: "应用筛选", viewDetails: "查看详情", bookNow: "立即预订", from: "起价", perPerson: "每人", left: "剩余 {{count}} 个名额", available: "可预订", limited: "名额有限", limitedSpots: "剩余名额有限", bookingOpen: "开放预订", all: "全部", historical: "历史", cultural: "文化", luxury: "奢华", group: "团体", private: "私人", educational: "教育", standard: "标准", premium: "高级", featured: "精选", bestseller: "畅销", new: "新品", any: "不限时长", lowHigh: "价格：从低到高", highLow: "价格：从高到低", ratingHigh: "评分：从高到低", popular: "最受欢迎", newest: "最新发布" },
  fr: { home: "Accueil", tours: "Circuits", title: "Découvrez nos circuits sélectionnés", description: "Découvrez des voyages historiques, culturels et luxueux conçus pour révéler la beauté authentique de l’Afrique.", filters: "Filtres", reset: "Tout réinitialiser", categories: "Catégories", destination: "Destination", destinationSearch: "Rechercher une destination…", duration: "Durée", price: "Fourchette de prix", style: "Style de circuit", availability: "Disponibilité", rating: "Note minimale", searchDestination: "Rechercher une destination", where: "Où en Afrique ?", category: "Catégorie", allCategories: "Toutes les catégories", travelDate: "Date du voyage", selectDate: "Choisir une date", anyDuration: "Toute durée", clear: "Effacer", search: "Rechercher", found_one: "{{count}} circuit trouvé", found_other: "{{count}} circuits trouvés", apply: "Appliquer les filtres", viewDetails: "Voir les détails", bookNow: "Réserver", from: "À partir de", perPerson: "par personne", left: "{{count}} disponibles", available: "Disponible", limited: "Limité", limitedSpots: "Places limitées", bookingOpen: "Réservations ouvertes", all: "Tous", historical: "Historique", cultural: "Culturel", luxury: "Luxe", group: "Groupe", private: "Privé", educational: "Éducatif", standard: "Standard", premium: "Premium", featured: "À la une", bestseller: "Meilleure vente", new: "Nouveau", any: "Toute durée", lowHigh: "Prix croissant", highLow: "Prix décroissant", ratingHigh: "Note décroissante", popular: "Plus populaires", newest: "Plus récents" }
}

const educational = {
  en: { badge: "For Local Students", notice: "This educational package is designed for local students in Ghana." },
  de: { badge: "Für einheimische Studierende", notice: "Dieses Bildungspaket richtet sich an einheimische Studierende in Ghana." },
  es: { badge: "Para estudiantes locales", notice: "Este paquete educativo está diseñado para estudiantes locales de Ghana." },
  "zh-CN": { badge: "面向本地学生", notice: "此教育套餐专为加纳本地学生设计。" },
  fr: { badge: "Pour les étudiants locaux", notice: "Ce forfait éducatif est destiné aux étudiants locaux du Ghana." },
}

const hotels = {
  en: { nav:"Hotels",eyebrow:"Curated stays",title:"Luxury Hotels & Stays in Ghana",subtitle:"Discover hand-picked hotels, resorts and heritage stays for your journey through Ghana.",search:"Search by hotel or destination",noMatches:"No hotels match your filters.",noReviews:"No reviews yet",from:"From",viewDetails:"View Details",whatsapp:"Contact Hotel on WhatsApp",amenities:"Amenities",nearby:"Nearby Attractions",reviews:"Guest Reviews",writeReview:"Write a Review",submitReview:"Submit Review" },
  de: { nav:"Hotels",eyebrow:"Ausgewählte Unterkünfte",title:"Luxushotels und Unterkünfte in Ghana",subtitle:"Entdecken Sie ausgewählte Hotels, Resorts und historische Unterkünfte in Ghana.",search:"Hotel oder Reiseziel suchen",noMatches:"Keine Hotels entsprechen Ihren Filtern.",noReviews:"Noch keine Bewertungen",from:"Ab",viewDetails:"Details ansehen",whatsapp:"Hotel über WhatsApp kontaktieren",amenities:"Ausstattung",nearby:"Sehenswürdigkeiten in der Nähe",reviews:"Gästebewertungen",writeReview:"Bewertung schreiben",submitReview:"Bewertung senden" },
  es: { nav:"Hoteles",eyebrow:"Estancias seleccionadas",title:"Hoteles y estancias de lujo en Ghana",subtitle:"Descubre hoteles, resorts y estancias patrimoniales seleccionados en Ghana.",search:"Buscar hotel o destino",noMatches:"Ningún hotel coincide con tus filtros.",noReviews:"Aún no hay reseñas",from:"Desde",viewDetails:"Ver detalles",whatsapp:"Contactar por WhatsApp",amenities:"Servicios",nearby:"Atracciones cercanas",reviews:"Reseñas de huéspedes",writeReview:"Escribir una reseña",submitReview:"Enviar reseña" },
  "zh-CN": { nav:"酒店",eyebrow:"精选住宿",title:"加纳豪华酒店与住宿",subtitle:"探索加纳精选酒店、度假村与文化遗产住宿。",search:"搜索酒店或目的地",noMatches:"没有符合筛选条件的酒店。",noReviews:"暂无评论",from:"起价",viewDetails:"查看详情",whatsapp:"通过 WhatsApp 联系酒店",amenities:"设施",nearby:"附近景点",reviews:"宾客评论",writeReview:"撰写评论",submitReview:"提交评论" },
  fr: { nav:"Hôtels",eyebrow:"Séjours sélectionnés",title:"Hôtels et séjours de luxe au Ghana",subtitle:"Découvrez des hôtels, resorts et séjours patrimoniaux sélectionnés au Ghana.",search:"Rechercher un hôtel ou une destination",noMatches:"Aucun hôtel ne correspond à vos filtres.",noReviews:"Aucun avis",from:"À partir de",viewDetails:"Voir les détails",whatsapp:"Contacter l'hôtel sur WhatsApp",amenities:"Équipements",nearby:"Attractions à proximité",reviews:"Avis des clients",writeReview:"Écrire un avis",submitReview:"Envoyer l'avis" },
}

export const routeTranslations = Object.fromEntries(Object.entries(tours).map(([language, values]) => [language, {
  toursPage: values,
  tourBadges: { forLocalStudents: educational[language as keyof typeof educational].badge },
  educationalTours: { localStudentNotice: educational[language as keyof typeof educational].notice },
  hotels: hotels[language as keyof typeof hotels],
}])) as Record<string, { toursPage: Record<string, string>; tourBadges: { forLocalStudents: string }; educationalTours: { localStudentNotice: string } }>
