import { useEffect, useState } from "react"
import type { Page } from "./App"
import { AdminShell } from "./AdminProductsPage"
import { adminBookingApi, type Booking } from "./api"
export default function AdminBookingsPage({onNavigate}:{onNavigate:(page:Page)=>void}){
  const [items,setItems]=useState<Booking[]>([]),[summary,setSummary]=useState<Record<string,number>>({}),[query,setQuery]=useState("")
  useEffect(()=>{adminBookingApi.list({limit:100}).then(result=>{setItems(result.data.bookings);setSummary(result.data.summary)})},[])
  const shown=items.filter(item=>`${item.booking_reference} ${item.customer.full_name} ${item.tour.title}`.toLowerCase().includes(query.toLowerCase()))
  return <AdminShell title="Bookings" active="Bookings" onNavigate={onNavigate}><p className="eyebrow">Booking workflow</p><h1 className="page-title">Bookings</h1><p className="sub">Review requests, discuss requirements, issue invoices and monitor payments.</p><div className="metric-grid">{[["Total",summary.total||0],["Pending Review",summary.pending_review||0],["Awaiting Payment",summary.awaiting_payment||0],["Confirmed",summary.confirmed||0]].map(item=><div className="admin-metric" key={item[0]}><p>{item[0]}</p><b>{item[1]}</b></div>)}</div><input className="admin-input my-5 w-full" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reference, customer or tour…"/><div className="admin-table-card overflow-x-auto"><table className="admin-table min-w-[1100px]"><thead><tr>{["Reference","Customer","Tour","Request Date","Booking Status","Payment Status","Last Activity","Action"].map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{shown.map(booking=><tr key={booking.id}><td><b>{booking.booking_reference}</b>{booking.admin_unread&&<span className="ml-2 inline-block h-2 w-2 animate-pulse rounded-full bg-[#C6A15B]"/>}</td><td><b>{booking.customer.full_name}</b><small className="block">{booking.customer.email}</small></td><td><b>{booking.tour.title}</b><small className="block">{booking.workflow==="flyer_request"?"Flyer request":booking.package?.name}</small></td><td>{new Date(booking.created_at).toLocaleDateString()}</td><td><span className="capitalize">{booking.booking_status.replaceAll("_"," ")}</span></td><td><span className="capitalize">{booking.payment_status.replaceAll("_"," ")}</span></td><td>{new Date(booking.last_activity_at||booking.created_at).toLocaleString()}</td><td><button className="admin-black" onClick={()=>{sessionStorage.setItem("kobani_admin_booking_id",booking.id);onNavigate("admin-booking-detail")}}>View</button></td></tr>)}</tbody></table></div></AdminShell>
}
