import { useEffect, useState } from "react"
import type { Page } from "./App"
import { AdminShell } from "./AdminProductsPage"
import { adminCustomerApi, type AdminCustomer } from "./api"
const money = (n = 0) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n / 100)
const date = (v?: string) => v ? new Date(v).toLocaleString("en-GB", { dateStyle: "medium" }) : "—"
export default function AdminCustomerProfilePage({ onNavigate }: { onNavigate: (p: Page) => void }) {
  const id = window.location.pathname.split("/admin/customers/")[1] || sessionStorage.getItem("kobani_admin_customer_id") || ""
  const [customer, setCustomer] = useState<AdminCustomer | null>(null), [error, setError] = useState(""), [editing, setEditing] = useState(false)
  const [form, setForm] = useState({ full_name: "", phone: "", country: "" })
  const load = async () => { try { const r = await adminCustomerApi.get(id); setCustomer(r.data.customer); setForm({ full_name: r.data.customer.full_name, phone: r.data.customer.phone, country: r.data.customer.country }) } catch { setError("Customer could not be loaded.") } }
  useEffect(() => { if (id) void load(); else setError("No customer was selected.") }, [id])
  const save = async () => { const r = await adminCustomerApi.update(id, form); setCustomer(r.data.customer); setEditing(false) }
  const openBooking = (bookingId: string) => { sessionStorage.setItem("kobani_admin_booking_id", bookingId); window.history.pushState({}, "", `/admin/bookings/${bookingId}`); onNavigate("admin-booking-detail") }
  return <AdminShell title="Customer profile" active="Customers" onNavigate={onNavigate}>
    <button onClick={() => { window.history.pushState({}, "", "/admin/customers"); onNavigate("admin-customers") }} className="admin-outline mb-5">← Back to customers</button>
    {error ? <div className="bg-red-50 border border-red-200 rounded-xl p-5 text-red-700">{error}</div> : !customer ? <div className="p-12 text-center">Loading customer…</div> : <>
      <section className="bg-white border rounded-2xl p-5 sm:p-7 flex flex-col md:flex-row gap-4 md:items-center"><span className="w-16 h-16 rounded-full bg-[#C6A15B] grid place-items-center font-bold text-xl">{customer.full_name.split(/\s+/).map(x => x[0]).join("").slice(0, 2)}</span><div className="flex-1"><h1 className="page-title">{customer.full_name}</h1><p className="sub">{customer.email} · {customer.country || "Country not set"} · Joined {date(customer.created_at)}</p></div><span className={`pill ${customer.status === "active" ? "success" : "warning"}`}>{customer.status}</span><button onClick={() => setEditing(true)} className="admin-outline">Edit contact</button></section>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-5">{[["Bookings", customer.total_bookings], ["Upcoming", customer.upcoming_bookings], ["Lifetime value", money(customer.lifetime_value_minor)], ["Outstanding", money(customer.outstanding_minor)]].map(x => <div className="admin-metric" key={x[0]}><p>{x[0]}</p><b>{x[1]}</b></div>)}</div>
      <div className="grid xl:grid-cols-[1.5fr_.8fr] gap-5 mt-5"><section className="admin-table-card"><div className="table-top"><b>Booking history</b></div><div className="overflow-x-auto"><table className="admin-table min-w-[700px]"><thead><tr>{["Reference", "Tour", "Departure", "Total", "Balance", "Status"].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{customer.bookings?.length ? customer.bookings.map(b => <tr key={b.id}><td><button className="font-bold hover:text-[#987437]" onClick={() => openBooking(b.id)}>{b.booking_reference}</button></td><td>{b.tour.title}</td><td>{date(b.departure.start_date)}</td><td>{money(b.total_minor)}</td><td>{money(b.balance_minor)}</td><td><span className="pill neutral">{b.booking_status}</span></td></tr>) : <tr><td colSpan={6} className="text-center py-10">No bookings yet.</td></tr>}</tbody></table></div></section><div className="space-y-5"><section className="bg-white border rounded-2xl p-5"><p className="eyebrow">Contact</p><p className="mt-3 font-bold break-all">{customer.email}</p><p className="text-sm mt-2">{customer.phone || "No phone number"}</p><p className="text-sm mt-2">{customer.country || "No country"}</p><p className="text-xs text-[#777] mt-4">Email {customer.email_verified ? "verified" : "not verified"}</p></section><section className="bg-white border rounded-2xl p-5"><p className="eyebrow">Refunds</p><b className="font-serif text-2xl block mt-2">{money(customer.refund_total_minor)}</b><p className="text-xs text-[#777]">{customer.refunds?.length || 0} refund record(s)</p></section></div></div>
      {editing && <div className="fixed inset-0 z-[80] bg-black/60 grid place-items-center p-4" onMouseDown={() => setEditing(false)}><form onSubmit={e => { e.preventDefault(); void save() }} onMouseDown={e => e.stopPropagation()} className="bg-white rounded-2xl p-6 w-full max-w-lg space-y-4"><h2 className="font-serif text-2xl font-bold">Edit customer</h2>{(["full_name", "phone", "country"] as const).map(k => <label className="form-field" key={k}><span>{k.replace("_", " ")}</span><input className="admin-input w-full" value={form[k]} onChange={e => setForm({ ...form, [k]: e.target.value })}/></label>)}<div className="flex justify-end gap-2"><button type="button" onClick={() => setEditing(false)} className="admin-outline">Cancel</button><button className="admin-gold">Save changes</button></div></form></div>}
    </>}
  </AdminShell>
}
