import { useEffect, useState } from "react"
import type { Page } from "./App"
import { AdminShell } from "./AdminProductsPage"
import { ApiError, adminPaymentApi, adminRefundApi, type AdminPayment, type AdminRefund } from "./api"
const money = (n = 0) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n / 100)
const date = (v?: string) => v ? new Date(v).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" }) : "—"
export default function AdminRefundsPage({ onNavigate }: { onNavigate: (p: Page) => void }) {
  const [items, setItems] = useState<AdminRefund[]>([]), [payments, setPayments] = useState<AdminPayment[]>([]), [summary, setSummary] = useState<Record<string, number>>({})
  const [selected, setSelected] = useState<AdminRefund | null>(null), [creating, setCreating] = useState(false), [search, setSearch] = useState(""), [status, setStatus] = useState("")
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [providerRef, setProviderRef] = useState("")
  const [form, setForm] = useState({ payment_id: "", amount: "", reason: "", notes: "" })
  const load = async () => { setError(""); try { const [r, p] = await Promise.all([adminRefundApi.list({ search, status }), adminPaymentApi.list()]); setItems(r.data.refunds); setSummary(r.data.summary); setPayments(p.data.payments.filter(x => x.fulfilled && x.amount_minor > x.refunded_minor)) } catch (e) { setError(e instanceof ApiError ? e.code.replaceAll("_", " ") : "Could not load refunds") } }
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer) }, [search, status])
  const create = async () => { setBusy(true); setError(""); try { await adminRefundApi.create(form); setCreating(false); setForm({ payment_id: "", amount: "", reason: "", notes: "" }); await load() } catch (e) { setError(e instanceof ApiError ? e.code.replaceAll("_", " ") : "Refund could not be created") } finally { setBusy(false) } }
  const act = async (action: string) => { if (!selected) return; setBusy(true); setError(""); try { const r = await adminRefundApi.action(selected.id, action, { notes: selected.notes || "", provider_refund_id: providerRef }); setSelected(r.data.refund); await load() } catch (e) { setError(e instanceof ApiError ? e.code.replaceAll("_", " ") : "Refund action failed") } finally { setBusy(false) } }
  const chosen = payments.find(x => x.id === form.payment_id)
  return <AdminShell title="Refunds" active="Refunds" onNavigate={onNavigate}>
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="eyebrow">Financial operations</p><h1 className="page-title">Refunds</h1><p className="sub">Request, approve and reconcile customer refunds with a complete audit trail.</p></div><button onClick={() => setCreating(true)} className="admin-gold">Create refund</button></div>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mt-6">{[["All records", summary.total || 0], ["Requested", summary.requested || 0], ["Approved / processing", summary.approved || 0], ["Completed", summary.refunded || 0], ["Refunded value", money(summary.refunded_minor)]].map(x => <div className="admin-metric" key={x[0]}><p>{x[0]}</p><b>{x[1]}</b></div>)}</div>
    <div className="filter-card"><input value={search} onChange={e => setSearch(e.target.value)} className="admin-input flex-1" placeholder="Search refund, customer or booking..."/><select value={status} onChange={e => setStatus(e.target.value)} className="admin-input"><option value="">All statuses</option>{["requested", "approved", "processing", "refunded", "rejected"].map(x => <option key={x}>{x}</option>)}</select><button onClick={() => void load()} className="admin-outline">Refresh</button></div>
    {error && <div className="mb-4 p-4 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">{error}</div>}
    <section className="admin-table-card"><div className="table-top flex justify-between"><b>Refund ledger</b><span className="text-xs text-[#777]">{items.length} record{items.length === 1 ? "" : "s"}</span></div><div className="overflow-x-auto"><table className="admin-table min-w-[1100px]"><thead><tr>{["Reference", "Customer", "Booking / Tour", "Payment", "Amount", "Reason", "Requested", "Status", ""].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{items.length ? items.map(r => <tr key={r.id}><td><b>{r.refund_reference}</b></td><td><b>{r.customer_name}</b><small className="block text-[#999]">{r.customer_email}</small></td><td>{r.booking_reference}<small className="block text-[#999]">{r.tour_title}</small></td><td>{r.payment_reference}<small className="block text-[#999] capitalize">{r.provider}</small></td><td><b>{money(r.amount_minor)}</b><small className="block text-[#999]">{r.currency}</small></td><td><p className="max-w-60 line-clamp-2">{r.reason}</p></td><td>{date(r.created_at)}</td><td><span className={`pill ${r.status === "refunded" ? "success" : r.status === "requested" ? "warning" : "neutral"}`}>{r.status}</span></td><td><button onClick={() => { setSelected(r); setProviderRef(r.provider_refund_id || "") }} className="admin-outline !px-3 !py-2">Review</button></td></tr>) : <tr><td colSpan={9} className="text-center py-14 text-[#888]">No refund records match these filters.</td></tr>}</tbody></table></div></section>
    {creating && <div className="fixed inset-0 z-[80] bg-black/60 grid place-items-center p-4" onMouseDown={() => setCreating(false)}><form onSubmit={e => { e.preventDefault(); void create() }} onMouseDown={e => e.stopPropagation()} className="bg-white rounded-2xl p-6 w-full max-w-xl space-y-4"><div><p className="eyebrow">New request</p><h2 className="font-serif text-2xl font-bold">Create refund</h2></div><label className="form-field"><span>Successful payment</span><select required className="admin-input w-full" value={form.payment_id} onChange={e => setForm({ ...form, payment_id: e.target.value })}><option value="">Select a refundable payment</option>{payments.map(p => <option key={p.id} value={p.id}>{p.payment_reference} · {p.customer_name} · {money(p.amount_minor - p.refunded_minor)}</option>)}</select></label>{chosen && <p className="text-xs rounded-lg bg-[#F8F4EA] p-3">Available to refund: <b>{money(chosen.amount_minor - chosen.refunded_minor)}</b> for {chosen.booking_reference}</p>}<label className="form-field"><span>Refund amount</span><input required type="number" min="0.01" step="0.01" max={chosen ? (chosen.amount_minor - chosen.refunded_minor) / 100 : undefined} className="admin-input w-full" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })}/></label><label className="form-field"><span>Reason</span><textarea required minLength={5} className="admin-input w-full min-h-24" value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })}/></label><label className="form-field"><span>Internal notes (optional)</span><textarea className="admin-input w-full" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })}/></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setCreating(false)} className="admin-outline">Cancel</button><button disabled={busy} className="admin-gold">{busy ? "Creating…" : "Create request"}</button></div></form></div>}
    {selected && <div className="fixed inset-0 z-[80] bg-black/60 flex justify-end" onMouseDown={() => setSelected(null)}><section className="bg-[#F8F4EA] h-full w-full max-w-2xl overflow-y-auto" onMouseDown={e => e.stopPropagation()}><header className="bg-white border-b p-6 flex justify-between sticky top-0"><div><p className="eyebrow">Refund review</p><h2 className="font-serif text-2xl font-bold">{selected.refund_reference}</h2></div><button className="text-2xl" onClick={() => setSelected(null)}>×</button></header><div className="p-6 space-y-5"><section className="bg-white border rounded-2xl p-5 grid sm:grid-cols-2 gap-4 text-sm">{[["Customer", selected.customer_name], ["Booking", selected.booking_reference], ["Payment", selected.payment_reference], ["Provider", selected.provider], ["Amount", money(selected.amount_minor)], ["Status", selected.status], ["Requested", date(selected.created_at)], ["Completed", date(selected.completed_at)]].map(x => <div key={x[0]}><small className="text-[#999] block">{x[0]}</small><b className="capitalize">{x[1]}</b></div>)}</section><section className="bg-white border rounded-2xl p-5"><p className="eyebrow">Reason</p><p className="mt-3 leading-6">{selected.reason}</p></section>{["approved", "processing"].includes(selected.status) && <label className="form-field"><span>Provider refund reference {selected.provider === "paystack" ? "(required before completion)" : "(optional)"}</span><input className="admin-input w-full bg-white" value={providerRef} onChange={e => setProviderRef(e.target.value)} placeholder="Reference returned by the payment provider"/></label>}</div><footer className="sticky bottom-0 bg-white border-t p-5 flex flex-wrap gap-2">{selected.status === "requested" && <><button disabled={busy} onClick={() => void act("reject")} className="admin-outline text-red-700">Reject</button><button disabled={busy} onClick={() => void act("approve")} className="admin-gold ml-auto">Approve</button></>}{selected.status === "approved" && <><button disabled={busy} onClick={() => void act("processing")} className="admin-outline ml-auto">Mark processing</button><button disabled={busy || (selected.provider === "paystack" && !providerRef.trim())} onClick={() => void act("complete")} className="admin-gold">Complete refund</button></>}{selected.status === "processing" && <button disabled={busy || (selected.provider === "paystack" && !providerRef.trim())} onClick={() => void act("complete")} className="admin-gold ml-auto">Complete refund</button>}</footer></section></div>}
  </AdminShell>
}
