import { useEffect, useState } from "react"
import type { Page } from "./App"
import { AdminShell } from "./AdminProductsPage"
import { ApiError, subscriberApi, type Subscriber } from "./api"

const date = (value?: string) => value ? new Date(value).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" }) : "—"

export default function AdminSubscribersPage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const [items, setItems] = useState<Subscriber[]>([]), [summary, setSummary] = useState<Record<string, number>>({})
  const [search, setSearch] = useState(""), [status, setStatus] = useState(""), [country, setCountry] = useState(""), [loading, setLoading] = useState(true), [error, setError] = useState("")
  const load = async () => { setLoading(true); setError(""); try { const result = await subscriberApi.list({ search, status, country }); setItems(result.data.subscribers); setSummary(result.data.summary) } catch (e) { setError(e instanceof ApiError ? e.code.replaceAll("_", " ") : "Subscribers could not be loaded") } finally { setLoading(false) } }
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer) }, [search, status, country])
  const act = async (item: Subscriber) => { try { await subscriberApi.action(item.id, item.status === "active" ? "unsubscribe" : "reactivate"); await load() } catch (e) { setError(e instanceof ApiError ? e.code.replaceAll("_", " ") : "Subscriber could not be updated") } }
  const countries = [...new Set(items.map(item => item.country_code).filter(value => value && value !== "Unknown"))].sort()
  return <AdminShell title="Subscribers" active="Subscribers" onNavigate={onNavigate}>
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="eyebrow">Audience growth</p><h1 className="page-title">Newsletter Subscribers</h1><p className="sub">People who requested KOBANI travel stories, tour launches and heritage insights.</p></div><a href={subscriberApi.exportUrl()} className="admin-outline text-center">Export CSV</a></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-6">{[["Total subscribers", summary.total || 0], ["Active", summary.active || 0], ["Unsubscribed", summary.unsubscribed || 0], ["Countries", summary.countries || 0]].map(item => <div className="admin-metric" key={item[0]}><p>{item[0]}</p><b>{item[1]}</b></div>)}</div>
    <div className="filter-card"><input value={search} onChange={event => setSearch(event.target.value)} className="admin-input flex-1 min-w-52" placeholder="Search email or location..."/><select value={status} onChange={event => setStatus(event.target.value)} className="admin-input"><option value="">All statuses</option><option value="active">Active</option><option value="unsubscribed">Unsubscribed</option></select><select value={country} onChange={event => setCountry(event.target.value)} className="admin-input"><option value="">All countries</option>{countries.map(value => <option key={value}>{value}</option>)}</select><button onClick={() => void load()} className="admin-outline">Refresh</button></div>
    {error && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <section className="admin-table-card"><div className="table-top flex justify-between"><b>Subscriber directory</b><span className="text-xs text-[#777]">{items.length} result{items.length === 1 ? "" : "s"}</span></div><div className="overflow-x-auto"><table className="admin-table min-w-[900px]"><thead><tr>{["Email", "Location", "Country", "Source", "Subscribed", "Status", "Action"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={7} className="py-14 text-center">Loading subscribers…</td></tr> : items.length === 0 ? <tr><td colSpan={7} className="py-14 text-center text-[#888]">No subscribers match these filters.</td></tr> : items.map(item => <tr key={item.id}><td><b>{item.email}</b></td><td>{item.location || "Unknown"}<small className="block text-[#999]">{[item.city, item.region].filter(Boolean).join(", ") || "Location unavailable"}</small></td><td>{item.country_code || "Unknown"}</td><td className="capitalize">{item.source.replaceAll("_", " ")}</td><td>{date(item.subscribed_at)}</td><td><span className={`pill ${item.status === "active" ? "success" : "neutral"}`}>{item.status}</span></td><td><button onClick={() => void act(item)} className="admin-outline !px-3 !py-2">{item.status === "active" ? "Unsubscribe" : "Reactivate"}</button></td></tr>)}</tbody></table></div></section>
  </AdminShell>
}
