import { useEffect, useState } from "react"
import type { Page } from "./App"
import { AdminShell } from "./AdminProductsPage"
import { ApiError, adminPaymentApi, type AdminPayment } from "./api"
const money = (n = 0) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n / 100)
const date = (v?: string) => v ? new Date(v).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" }) : "—"
export default function AdminFinancePage({ onNavigate }: { onNavigate: (p: Page) => void }) {
  const [items, setItems] = useState<AdminPayment[]>([]), [summary, setSummary] = useState<Record<string, number>>({}), [selected, setSelected] = useState<AdminPayment | null>(null)
  const [search, setSearch] = useState(""), [status, setStatus] = useState(""), [provider, setProvider] = useState(""), [type, setType] = useState("")
  const [loading, setLoading] = useState(true), [error, setError] = useState("")
  const load = async () => { setLoading(true); setError(""); try { const r = await adminPaymentApi.list({ search, status, provider, payment_type: type }); setItems(r.data.payments); setSummary(r.data.summary) } catch (e) { setError(e instanceof ApiError ? e.code.replaceAll("_", " ") : "Could not load payments") } finally { setLoading(false) } }
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer) }, [search, status, provider, type])
  const verify = async (p: AdminPayment) => { try { await adminPaymentApi.verify(p.id); await load(); setSelected(null) } catch (e) { setError(e instanceof ApiError ? e.code.replaceAll("_", " ") : "Verification failed") } }
  return <AdminShell title="Payments" active="Payments" onNavigate={onNavigate}>
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="eyebrow">Financial operations</p><h1 className="page-title">Payments</h1><p className="sub">A live ledger of booking payments and refunds.</p></div><button onClick={() => void load()} className="admin-outline">Refresh ledger</button></div>
    <div className="grid grid-cols-2 xl:grid-cols-6 gap-3 mt-6">{[["Transactions", summary.total || 0], ["Successful", summary.successful || 0], ["Pending", summary.pending || 0], ["Gross", money(summary.gross_minor)], ["Refunded", money(summary.refunded_minor)], ["Net collected", money(summary.net_minor)]].map(x => <div className="admin-metric" key={x[0]}><p>{x[0]}</p><b>{x[1]}</b></div>)}</div>
    <div className="filter-card"><input className="admin-input flex-1 min-w-52" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search reference, customer or booking..."/><select className="admin-input" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="success">Successful</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="partially_refunded">Partially refunded</option><option value="refunded">Refunded</option></select><select className="admin-input" value={provider} onChange={e => setProvider(e.target.value)}><option value="">All providers</option><option value="paystack">Paystack</option><option value="manual">Manual</option></select><select className="admin-input" value={type} onChange={e => setType(e.target.value)}><option value="">All payment types</option><option value="deposit">Deposit</option><option value="balance">Balance</option><option value="full">Full payment</option></select></div>
    {error && <div className="mb-4 p-4 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">{error}</div>}
    <section className="admin-table-card"><div className="table-top flex justify-between"><b>Payment ledger</b><span className="text-xs text-[#777]">{items.length} record{items.length === 1 ? "" : "s"}</span></div><div className="overflow-x-auto"><table className="admin-table min-w-[1150px]"><thead><tr>{["Reference", "Customer", "Booking / Tour", "Provider", "Type", "Amount", "Refunded", "Date", "Status", ""].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={10} className="text-center py-14">Loading payments…</td></tr> : items.length === 0 ? <tr><td colSpan={10} className="text-center py-14 text-[#888]">No payment records match these filters.</td></tr> : items.map(p => <tr key={p.id}><td><b>{p.payment_reference}</b><small className="block text-[#999]">{p.provider_transaction_id || "—"}</small></td><td><b>{p.customer_name}</b><small className="block text-[#999]">{p.customer_email}</small></td><td>{p.booking_reference}<small className="block text-[#999]">{p.tour_title}</small></td><td className="capitalize">{p.provider}</td><td className="capitalize">{p.payment_type}</td><td><b>{money(p.amount_minor)}</b><small className="block text-[#999]">{p.currency}</small></td><td>{money(p.refunded_minor)}</td><td>{date(p.paid_at || p.created_at)}</td><td><span className={`pill ${p.fulfilled ? "success" : p.status === "failed" ? "warning" : "neutral"}`}>{p.status.replaceAll("_", " ")}</span></td><td><button className="admin-outline !px-3 !py-2" onClick={() => setSelected(p)}>View</button></td></tr>)}</tbody></table></div></section>
    {selected && <div className="fixed inset-0 z-[80] bg-black/60 flex justify-end" onMouseDown={() => setSelected(null)}><section className="bg-[#F8F4EA] h-full w-full max-w-xl p-6 overflow-y-auto" onMouseDown={e => e.stopPropagation()}><div className="flex justify-between"><div><p className="eyebrow">Payment details</p><h2 className="font-serif text-2xl font-bold">{selected.payment_reference}</h2></div><button onClick={() => setSelected(null)} className="text-2xl">×</button></div><div className="bg-white border rounded-2xl p-5 mt-6 space-y-4 text-sm">{[["Customer", selected.customer_name], ["Booking", selected.booking_reference], ["Tour", selected.tour_title], ["Provider", selected.provider], ["Method", selected.method || "—"], ["Amount", money(selected.amount_minor)], ["Refunded", money(selected.refunded_minor)], ["Status", selected.status], ["Created", date(selected.created_at)]].map(x => <div className="flex justify-between gap-5 border-b pb-3 last:border-0" key={x[0]}><span className="text-[#777]">{x[0]}</span><b className="text-right capitalize">{x[1]}</b></div>)}</div>{selected.provider === "paystack" && !selected.fulfilled && <button onClick={() => void verify(selected)} className="admin-gold w-full mt-5">Verify with Paystack</button>}</section></div>}
  </AdminShell>
}
