import { useCallback, useEffect, useMemo, useState } from "react"
import type { Page } from "./App"
import { AdminShell } from "./AdminProductsPage"
import { ApiError, adminDashboardApi, type DashboardSnapshot } from "./api"

const money = (minor: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(minor / 100)
const date = (value?: string) => value ? new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "—"
const stamp = (value?: string) => value ? new Date(value).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "—"

function Card({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="rounded-2xl bg-white border border-[#E6DFD2] overflow-hidden"><div className="px-5 py-4 border-b flex items-center justify-between"><h2 className="font-serif font-bold text-lg">{title}</h2>{action}</div>{children}</section>
}

export default function AdminDashboard({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const [data, setData] = useState<DashboardSnapshot | null>(null), [days, setDays] = useState(30), [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [error, setError] = useState("")
  const load = useCallback(async (quiet = false) => { quiet ? setRefreshing(true) : setLoading(true); setError(""); try { setData((await adminDashboardApi.get(days)).data) } catch (e) { setError(e instanceof ApiError ? e.code.replaceAll("_", " ") : "Dashboard data could not be loaded") } finally { setLoading(false); setRefreshing(false) } }, [days])
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(true), 15000); const visible = () => { if (!document.hidden) void load(true) }; document.addEventListener("visibilitychange", visible); window.addEventListener("focus", visible); return () => { clearInterval(timer); document.removeEventListener("visibilitychange", visible); window.removeEventListener("focus", visible) } }, [load])
  const maxBookings = Math.max(1, ...(data?.monthly.map(item => item.bookings) || [1]))
  const maxCountry = Math.max(1, ...(data?.top_countries.map(item => item.views) || [1]))
  const revenueCurrencies = useMemo(() => [...new Set(data?.monthly.flatMap(item => item.revenue.map(value => value.currency)) || [])], [data])
  const openBooking = (id: string) => { sessionStorage.setItem("kobani_admin_booking_id", id); window.history.pushState({}, "", `/admin/bookings/${id}`); onNavigate("admin-booking-detail") }
  const metrics = data ? [["Page views", data.metrics.page_views, `${data.metrics.unique_visitors} unique visitors`], ["New bookings", data.metrics.bookings, `${data.metrics.total_bookings} all time`], ["Customers", data.metrics.customers, "Registered and guest customers"], ["Subscribers", data.metrics.active_subscribers, "Active newsletter audience"], ["Open balances", data.metrics.open_balances, "Bookings awaiting payment"], ["Upcoming tours", data.metrics.upcoming_departures, "Scheduled departures"]] : []
  return <AdminShell title="Dashboard" active="Dashboard" onNavigate={onNavigate}>
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><div className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"/><p className="eyebrow">Live operations</p></div><h1 className="page-title">KOBANI Overview</h1><p className="sub">Live bookings, revenue, audience and operational workload from the backend.</p></div><div className="flex gap-2"><select value={days} onChange={event => setDays(Number(event.target.value))} className="admin-input"><option value={1}>Today</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={365}>Last 12 months</option></select><button onClick={() => void load(true)} disabled={refreshing} className="admin-outline">{refreshing ? "Refreshing…" : "Refresh now"}</button></div></div>
    {data && <p className="mt-3 text-[10px] text-[#888]">Automatically refreshes every 15 seconds · Last synced at {stamp(data.generated_at)}</p>}
    {error && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading && !data ? <div className="py-28 text-center text-[#777]">Loading the live dashboard…</div> : data && <>
      <section className="grid grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6 gap-4 mt-6">{metrics.map(item => <article key={item[0]} className="admin-metric"><p>{item[0]}</p><b>{item[1]}</b><small className="block mt-2 text-[#888]">{item[2]}</small></article>)}</section>
      <section className="grid xl:grid-cols-[1.15fr_.85fr] gap-5 mt-5"><Card title="Financial position" action={<button onClick={() => onNavigate("admin-finance")} className="text-xs font-bold text-[#987437]">Open payments →</button>}><div className="p-5 grid sm:grid-cols-2 gap-4">{data.finance.length ? data.finance.map(item => <div key={item.currency} className="rounded-xl bg-[#F8F4EA] p-4"><div className="flex justify-between"><p className="eyebrow">{item.currency}</p><span className="pill neutral">Live</span></div><b className="font-serif text-2xl block mt-2">{money(item.net_minor, item.currency)}</b><p className="text-xs text-[#777] mt-1">Net collected</p><div className="grid grid-cols-3 gap-2 mt-4 text-xs"><div><small className="text-[#999] block">Gross</small><b>{money(item.gross_minor, item.currency)}</b></div><div><small className="text-[#999] block">Refunded</small><b>{money(item.refunded_minor, item.currency)}</b></div><div><small className="text-[#999] block">Outstanding</small><b>{money(item.outstanding_minor, item.currency)}</b></div></div></div>) : <div className="sm:col-span-2 py-12 text-center text-sm text-[#888]">Financial totals will appear after the first successful payment.</div>}</div></Card>
      <Card title="Attention required"><div className="p-5 grid grid-cols-2 gap-3">{[["Unpaid bookings", data.pending.unpaid_bookings, "admin-bookings"], ["Refund requests", data.pending.refund_requests, "admin-refunds"], ["Held reservations", data.pending.held_reservations, "admin-bookings"], ["Draft articles", data.pending.draft_articles, "admin-articles"]].map(item => <button key={item[0]} onClick={() => onNavigate(item[2] as Page)} className="rounded-xl bg-[#F8F4EA] p-4 text-left hover:ring-1 ring-[#C6A15B]"><small className="text-[#777]">{item[0]}</small><b className="font-serif text-2xl block mt-2">{item[1]}</b></button>)}</div></Card></section>
      <section className="grid lg:grid-cols-2 gap-5 mt-5"><Card title="Bookings by month"><div className="p-5"><div className="h-56 flex items-end gap-3 border-b">{data.monthly.map(item => <div key={item.month} className="flex-1 h-full flex flex-col justify-end items-center"><small className="mb-2 text-[#777]">{item.bookings}</small><div className="w-full max-w-12 rounded-t-lg bg-[#C6A15B] min-h-1" style={{ height: `${Math.max(3, item.bookings / maxBookings * 82)}%` }}/></div>)}</div><div className="grid grid-cols-6 text-center text-[10px] text-[#888] mt-2">{data.monthly.map(item => <span key={item.month}>{item.label}</span>)}</div></div></Card>
      <Card title="Collected revenue by month"><div className="p-5 space-y-4">{data.monthly.map(item => <div key={item.month} className="grid grid-cols-[45px_1fr] gap-3 items-center"><b className="text-xs">{item.label}</b><div className="flex flex-wrap gap-2">{revenueCurrencies.map(currency => { const value = item.revenue.find(x => x.currency === currency)?.amount_minor || 0; return <span key={currency} className="rounded-lg bg-[#F8F4EA] px-3 py-2 text-xs"><b>{money(value, currency)}</b></span> })}{!revenueCurrencies.length && <span className="text-xs text-[#999]">No payments</span>}</div></div>)}</div></Card></section>
      <section className="grid xl:grid-cols-[1.4fr_.6fr] gap-5 mt-5"><Card title="Recent bookings" action={<button onClick={() => onNavigate("admin-bookings")} className="text-xs font-bold text-[#987437]">View all →</button>}><div className="overflow-x-auto"><table className="admin-table min-w-[800px]"><thead><tr>{["Reference", "Customer", "Tour", "Departure", "Value", "Status"].map(value => <th key={value}>{value}</th>)}</tr></thead><tbody>{data.recent_bookings.length ? data.recent_bookings.map(booking => <tr key={booking.id}><td><button onClick={() => openBooking(booking.id)} className="font-bold hover:text-[#987437]">{booking.booking_reference}</button></td><td>{booking.customer.full_name}<small className="block text-[#999]">{booking.customer.email}</small></td><td>{booking.tour.title}</td><td>{date(booking.departure.start_date)}</td><td><b>{money(booking.total_minor, booking.currency)}</b></td><td><span className="pill neutral">{booking.booking_status}</span></td></tr>) : <tr><td colSpan={6} className="py-12 text-center text-[#888]">No bookings yet.</td></tr>}</tbody></table></div></Card>
      <Card title="Visitors by country"><div className="p-5 space-y-4">{data.top_countries.length ? data.top_countries.map(item => <div key={item.country}><div className="flex justify-between text-xs"><b>{item.country}</b><span>{item.views} views</span></div><div className="h-2 bg-[#EEE7D9] rounded-full mt-2 overflow-hidden"><i className="block h-full bg-[#C6A15B] rounded-full" style={{ width: `${item.views / maxCountry * 100}%` }}/></div></div>) : <div className="py-12 text-center text-sm text-[#888]">Visitor locations will appear as analytics are collected.</div>}</div></Card></section>
      <Card title="Recent payments" action={<button onClick={() => onNavigate("admin-finance")} className="text-xs font-bold text-[#987437]">Payment ledger →</button>}><div className="overflow-x-auto"><table className="admin-table min-w-[900px]"><thead><tr>{["Reference", "Customer", "Booking", "Provider", "Amount", "Date", "Status"].map(value => <th key={value}>{value}</th>)}</tr></thead><tbody>{data.recent_payments.length ? data.recent_payments.map(payment => <tr key={payment.id}><td><b>{payment.payment_reference}</b></td><td>{payment.customer_name}</td><td>{payment.booking_reference}</td><td className="capitalize">{payment.provider}</td><td><b>{money(payment.amount_minor, payment.currency)}</b></td><td>{date(payment.paid_at || payment.created_at)}</td><td><span className={`pill ${payment.fulfilled ? "success" : "neutral"}`}>{payment.status}</span></td></tr>) : <tr><td colSpan={7} className="py-12 text-center text-[#888]">No payment activity yet.</td></tr>}</tbody></table></div></Card>
    </>}
  </AdminShell>
}
