import { useEffect, useState } from "react"
import type { Page } from "./App"
import { contactMessageApi, type ContactMessage } from "./api"
import { AdminShell } from "./AdminProductsPage"

const when = (value: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value))

export default function AdminInboxPage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const [messages,setMessages]=useState<ContactMessage[]>([]),[selected,setSelected]=useState<ContactMessage|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[unread,setUnread]=useState(0)
  const load=async()=>{setLoading(true);setError("");try{const result=await contactMessageApi.adminList({status,search});setMessages(result.data.messages);setUnread(result.data.unread_count)}catch{setError("Messages could not be loaded. Please try again.")}finally{setLoading(false)}}
  useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[search,status])
  const open=async(message:ContactMessage)=>{try{const item=(await contactMessageApi.adminGet(message.id)).data.message;setSelected(item);setMessages(rows=>rows.map(row=>row.id===item.id?{...row,is_read:true}:row));setUnread(value=>Math.max(0,value-(message.is_read?0:1)));window.dispatchEvent(new Event("kobani:messages-count"))}catch{setError("This message could not be opened.")}}
  const markUnread=async()=>{if(!selected)return;await contactMessageApi.markRead(selected.id,false);setSelected({...selected,is_read:false});setMessages(rows=>rows.map(row=>row.id===selected.id?{...row,is_read:false}:row));setUnread(value=>value+1);window.dispatchEvent(new Event("kobani:messages-count"))}
  return <AdminShell title="Messages" active="Messages" onNavigate={onNavigate}><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Customer enquiries</p><h1 className="page-title">Messages</h1><p className="sub">Every message submitted through the Contact Us page appears here.</p></div><div className="rounded-xl bg-[#C6A15B]/15 px-4 py-2 text-xs font-bold text-[#8A682E]">{unread} unread</div></div>
  <div className="grid min-h-[680px] overflow-hidden rounded-2xl border border-[#E4DCCF] bg-white lg:grid-cols-[380px_1fr]">
    <section className={`${selected?"hidden lg:block":"block"} border-r`}><div className="space-y-3 border-b p-4"><input className="admin-input w-full" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search name, email or message…"/><div className="flex gap-2"><select className="admin-input flex-1" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All messages</option><option value="unread">Unread</option><option value="read">Read</option></select><button onClick={()=>void load()} className="admin-outline">Refresh</button></div></div>
    {loading?<div className="space-y-3 p-4">{[1,2,3,4].map(x=><div key={x} className="h-24 animate-pulse rounded-xl bg-[#F3EEE4]"/>)}</div>:error?<div role="alert" className="p-6 text-sm text-[#9B3E3E]">{error}<button onClick={()=>void load()} className="admin-outline mt-4 block">Try again</button></div>:messages.length===0?<div className="p-10 text-center text-sm text-[#888]">No contact messages found.</div>:<div className="max-h-[590px] overflow-y-auto">{messages.map(message=><button key={message.id} onClick={()=>void open(message)} className={`w-full border-b p-4 text-left transition hover:bg-[#FCFAF5] ${message.is_read?"":"bg-[#C6A15B]/5"}`}><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${message.is_read?"bg-transparent":"bg-[#C6A15B]"}`}/><b className="flex-1 truncate text-sm">{message.name}</b><small className="text-[9px] text-[#999]">{when(message.created_at)}</small></div><p className="mt-1 truncate text-xs font-semibold">{message.subject||message.enquiry_type}</p><p className="mt-1 line-clamp-2 text-xs text-[#888]">{message.preview}</p></button>)}</div>}</section>
    <article className={`${selected?"block":"hidden lg:grid"} min-w-0 place-items-center`}>{selected?<div className="h-full w-full"><header className="border-b p-5"><button onClick={()=>setSelected(null)} className="admin-outline mb-4 lg:hidden">← Back</button><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#C6A15B] font-bold">{selected.name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}</span><div className="min-w-0"><h2 className="font-serif text-xl font-bold">{selected.subject||selected.enquiry_type}</h2><p className="text-xs text-[#777]">{selected.name} · <a className="text-[#9A7636] underline" href={`mailto:${selected.email}`}>{selected.email}</a>{selected.phone?` · ${selected.phone}`:""}</p><p className="mt-1 text-[10px] text-[#999]">{selected.enquiry_type} · {when(selected.created_at)}</p></div></div><div className="mt-4 flex gap-2"><a href={`mailto:${selected.email}?subject=${encodeURIComponent(`Re: ${selected.subject||selected.enquiry_type}`)}`} className="admin-gold">Reply by email</a><button onClick={()=>void markUnread()} className="admin-outline">Mark unread</button></div></header><div className="whitespace-pre-wrap p-6 text-sm leading-7 text-[#292621]">{selected.message}</div></div>:<div className="text-center text-[#999]"><div className="text-4xl">✉</div><p className="mt-3 text-sm">Select a message to read it</p></div>}</article>
  </div></AdminShell>
}
