import { type ChangeEvent, useEffect, useState } from "react"
import type { Page } from "./App"
import { AdminShell } from "./AdminProductsPage"
import { ApiError, resolveMediaUrl, type ArticleImage, type TourCategory, tourApi } from "./api"

const errorText = (error: unknown) => error instanceof ApiError ? error.code.replaceAll("_", " ") : "Unable to save tour"
export default function AdminCreateTourPage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const editId = sessionStorage.getItem("kobani_edit_tour_id")
  const [categories, setCategories] = useState<TourCategory[]>([])
  const [form, setForm] = useState({ title: "", destination: "", category_id: "", notes: "", status: "draft" })
  const [flyer, setFlyer] = useState<ArticleImage | undefined>(), [gallery, setGallery] = useState<ArticleImage[]>([])
  const [uploading, setUploading] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState("")
  useEffect(() => { tourApi.categories().then(result => setCategories(result.data.categories)); if (editId) tourApi.adminDetail(editId).then(result => { const tour=result.data.tour; setForm({ title:tour.title,destination:tour.destination,category_id:tour.category?.id||"",notes:tour.notes||"",status:tour.status }); setFlyer(tour.flyer_image||tour.featured_image); setGallery(tour.gallery||[]) }).catch(error => setError(errorText(error))) }, [editId])
  const upload = async (files: FileList | null, main = false) => { if (!files?.length) return; setUploading(true); setError(""); try { const images=[]; for (const file of Array.from(files)) images.push((await tourApi.uploadImage(file)).data.image); if (main) setFlyer(images[0]); else setGallery(current => [...current,...images]) } catch (error) { setError(errorText(error)) } finally { setUploading(false) } }
  const save = async (status: "draft"|"published") => { if (!form.title.trim()||!form.destination.trim()||!form.category_id) { setError("Title, location and category are required."); return } if (status==="published"&&!flyer) { setError("Upload the main package flyer before publishing."); return } setSaving(true);setError(""); try { const payload={...form,status,booking_mode:"flyer_request" as const,country:"Ghana",flyer_image:flyer,featured_image:flyer,gallery}; if(editId) await tourApi.update(editId,payload); else await tourApi.create(payload); sessionStorage.removeItem("kobani_edit_tour_id");onNavigate("admin-tours") } catch(error){setError(errorText(error))} finally{setSaving(false)} }
  return <AdminShell title={editId?"Edit Tour":"Create Tour"} active="Tours" onNavigate={onNavigate}><div className="mx-auto max-w-5xl"><button onClick={()=>onNavigate("admin-tours")} className="text-xs text-[#777]">← Back to Tours</button><div className="mt-4"><p className="eyebrow">Flyer-based experience</p><h1 className="page-title">{editId?"Edit Tour":"Create Tour"}</h1><p className="sub">The flyer is the authoritative package presentation. Only essential catalogue information is required.</p></div>
  <section className="mt-6 rounded-2xl border border-[#E5DDCE] bg-white p-5 sm:p-7"><div className="grid gap-5 md:grid-cols-2"><label className="form-field"><span>Tour Title *</span><input className="admin-input w-full" value={form.title} onChange={e=>setForm(x=>({...x,title:e.target.value}))} placeholder="Homowo Festival in Accra"/></label><label className="form-field"><span>Location *</span><input className="admin-input w-full" value={form.destination} onChange={e=>setForm(x=>({...x,destination:e.target.value}))} placeholder="Accra, Greater Accra Region"/></label><label className="form-field md:col-span-2"><span>Category *</span><select className="admin-input w-full" value={form.category_id} onChange={e=>setForm(x=>({...x,category_id:e.target.value}))}><option value="">Select category</option>{categories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label></div>
  <div className="mt-6"><p className="text-xs font-bold">Main Package Flyer *</p><label className="mt-2 grid min-h-64 cursor-pointer place-items-center overflow-hidden rounded-2xl border-2 border-dashed border-[#D8CEBC] bg-[#FAF7F0] p-4 text-center">{flyer?<img src={resolveMediaUrl(flyer.url)} alt={flyer.alt_text||"Tour flyer preview"} className="max-h-[620px] w-full object-contain"/>:<span><b className="block">Upload Flyer</b><small className="text-[#777]">JPEG, PNG or WEBP · preserve readable quality</small></span>}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(e:ChangeEvent<HTMLInputElement>)=>void upload(e.target.files,true)}/></label>{flyer&&<button onClick={()=>setFlyer(undefined)} className="mt-2 text-xs text-red-700">Remove flyer</button>}</div>
  <label className="form-field mt-6"><span>Notes</span><textarea className="admin-input min-h-36 w-full resize-y" value={form.notes} onChange={e=>setForm(x=>({...x,notes:e.target.value}))} placeholder="Special booking instructions, group requirements or important customer information"/></label>
  <div className="mt-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">Additional Tour Pictures</p><small className="text-[#777]">Optional destination, hotel, transport and activity images</small></div><label className="admin-outline cursor-pointer">+ Add Pictures<input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>void upload(e.target.files)}/></label></div>{gallery.length>0&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{gallery.map((image,index)=><div className="relative rounded-xl border bg-[#F8F4EA] p-2" key={`${image.storage_key}-${index}`}><img src={resolveMediaUrl(image.url)} alt={image.alt_text||"Gallery preview"} className="h-36 w-full rounded-lg object-cover"/><button aria-label="Remove picture" onClick={()=>setGallery(items=>items.filter((_,i)=>i!==index))} className="absolute right-3 top-3 grid h-7 w-7 place-items-center rounded-full bg-black text-white">×</button></div>)}</div>}</div>
  {error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="mt-7 flex flex-wrap justify-end gap-3"><button disabled={saving||uploading} onClick={()=>void save("draft")} className="admin-outline disabled:opacity-50">Save Draft</button><button disabled={saving||uploading} onClick={()=>void save("published")} className="admin-gold disabled:opacity-50">{saving?"Saving…":uploading?"Uploading…":"Publish Experience"}</button></div></section></div></AdminShell>
}
