import { useEffect, useState } from "react"
import type { Page } from "./App"
import { AdminShell } from "./AdminProductsPage"
import { ApiError, resolveMediaUrl, tourApi, type Tour } from "./api"

const message=(error:unknown)=>error instanceof ApiError?error.code.replaceAll("_"," "):"Something went wrong"
export default function AdminToursPage({onNavigate}:{onNavigate:(page:Page)=>void}){
  const [items,setItems]=useState<Tour[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[notice,setNotice]=useState("")
  const load=async()=>{setLoading(true);try{setItems((await tourApi.adminList({search,status,limit:100})).data.tours)}catch(error){setNotice(message(error))}finally{setLoading(false)}}
  useEffect(()=>{const timer=setTimeout(()=>void load(),150);return()=>clearTimeout(timer)},[search,status])
  const edit=(tour:Tour)=>{sessionStorage.setItem("kobani_edit_tour_id",tour.id);onNavigate("admin-create-tour")}
  const action=async(tour:Tour,name:"publish"|"archive"|"restore")=>{try{await tourApi.action(tour.id,name);await load()}catch(error){setNotice(message(error))}}
  const remove=async(tour:Tour)=>{if(!confirm(`Delete “${tour.title}”?`))return;try{await tourApi.remove(tour.id);await load()}catch(error){setNotice(message(error))}}
  return <AdminShell title="Tours" active="Tours" onNavigate={onNavigate}><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Tour operations</p><h1 className="page-title">Tours</h1><p className="sub">Create and manage flexible flyer-based KOBANI experiences.</p></div><button onClick={()=>{sessionStorage.removeItem("kobani_edit_tour_id");onNavigate("admin-create-tour")}} className="admin-gold">+ Create New Tour</button></div>{notice&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm">{notice}</p>}<div className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-[1fr_220px]"><input className="admin-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title or location…"/><select className="admin-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></div><section className="admin-table-card mt-5 overflow-x-auto"><table className="admin-table min-w-[1050px]"><thead><tr>{["Flyer","Tour","Location","Category","Status","Created","Bookings / Requests","Actions"].map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{items.map(tour=><tr key={tour.id}><td>{tour.featured_image?<img src={resolveMediaUrl(tour.featured_image.url)} alt="" className={`h-20 w-24 rounded-xl bg-[#EEE7D9] ${tour.booking_mode==="flyer_request"?"object-contain":"object-cover"}`}/>:<div className="grid h-20 w-24 place-items-center rounded-xl bg-[#EEE7D9] text-[10px]">No flyer</div>}</td><td><b>{tour.title}</b><small className="block text-[#888]">{tour.booking_mode==="flyer_request"?"Flyer-based":"Legacy tour"}</small></td><td>{tour.destination}<small className="block">{tour.country}</small></td><td>{tour.category?.name}</td><td><span className="pill neutral capitalize">{tour.status}</span></td><td>{tour.created_at?new Date(tour.created_at).toLocaleDateString():"—"}</td><td>{tour.booking_count||0}</td><td><div className="flex flex-wrap gap-2"><button onClick={()=>{sessionStorage.setItem("kobani_selected_tour_slug",tour.slug);onNavigate("tour-details")}} className="admin-outline">View</button><button onClick={()=>edit(tour)} className="admin-outline">Edit</button>{tour.status==="published"?<button onClick={()=>void action(tour,"archive")} className="admin-outline">Unpublish</button>:<button onClick={()=>void action(tour,"publish")} className="admin-black">Publish</button>}<button onClick={()=>void remove(tour)} className="px-2 text-xs text-red-700">Delete</button></div></td></tr>)}</tbody></table>{loading&&<p className="p-10 text-center">Loading tours…</p>}{!loading&&!items.length&&<p className="p-10 text-center">No tours found.</p>}</section></AdminShell>
}
