import { useEffect, useState } from "react"
import type { Page } from "./App"
import { articleApi, resolveMediaUrl, type Article } from "./api"
import { useTranslation } from "react-i18next"
import SEO, { breadcrumbSchema, canonicalUrl, cleanDescription, DEFAULT_OG_IMAGE, ORGANIZATION_NAME } from "./seo"

const date = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "long" }).format(new Date(value)) : ""
export default function ArticleReadPage({ onNavigate }: { onNavigate: (p: Page) => void }) {
  const { i18n } = useTranslation()
  const slug = decodeURIComponent(location.pathname.split("/articles/")[1] || sessionStorage.getItem("kobani:selectedArticleSlug") || "")
  const [article, setArticle] = useState<Article | null>(null), [loading, setLoading] = useState(true), [notFound, setNotFound] = useState(false), [copied, setCopied] = useState(false)
  useEffect(() => { setLoading(true); setNotFound(false); articleApi.publicDetail(slug).then(response => setArticle(response.data.article)).catch(() => setNotFound(true)).finally(() => setLoading(false)) }, [slug,i18n.resolvedLanguage])
  const read = (next: Article) => { history.pushState({}, "", `/articles/${next.slug}`); location.reload() }
  if (loading) return <div className="mx-auto max-w-5xl space-y-5 px-4 py-20">{[1,2,3].map(i => <div key={i} className="h-24 animate-pulse rounded-2xl bg-[#EEE8DD]" />)}</div>
  if (notFound || !article) return <><SEO title="Article Not Found | KOBANI" description="The requested KOBANI article is unavailable." path={location.pathname} noindex nofollow/><div className="px-4 py-24 text-center"><h1 className="font-serif text-4xl font-bold">Article not found</h1><button onClick={() => onNavigate("articles")} className="mt-6 rounded-full bg-[#0B0B0B] px-6 py-3 text-xs font-bold text-white">Browse Articles</button></div></>
  const url = location.href
  const seo=article.seo||{},path=`/articles/${encodeURIComponent(article.slug)}`,description=cleanDescription(String(seo.description||seo.meta_description||article.excerpt)),image=article.featured_image?.url?resolveMediaUrl(article.featured_image.url):DEFAULT_OG_IMAGE
  const articleSchema={"@context":"https://schema.org","@type":"BlogPosting",headline:article.title,description,image:[image],mainEntityOfPage:canonicalUrl(path),author:{"@type":"Person",name:article.author.display_name},publisher:{"@type":"Organization",name:ORGANIZATION_NAME,logo:{"@type":"ImageObject",url:DEFAULT_OG_IMAGE}},...(article.published_at?{datePublished:article.published_at}:{}),...(article.updated_at?{dateModified:article.updated_at}:{})}
  return <article className="bg-[#FFFDF8] text-[#0B0B0B]"><SEO title={String(seo.title||seo.meta_title||`${article.title} | KOBANI Tours`)} description={description} path={path} image={image} imageAlt={article.featured_image?.alt_text||article.title} type="article" structuredData={[articleSchema,breadcrumbSchema([{name:"Home",path:"/"},{name:"Articles",path:"/articles"},{name:article.title,path}])]}/><header className="bg-[#0B0B0B] px-4 py-16 text-white sm:py-24"><div className="mx-auto max-w-4xl"><a href="/articles" onClick={event=>{event.preventDefault();onNavigate("articles")}} className="text-xs text-[#C6A15B]">Articles / {article.category.name}</a><h1 className="mt-5 font-serif text-4xl font-bold leading-tight sm:text-6xl">{article.title}</h1><p className="mt-6 max-w-3xl text-base leading-8 text-white/65">{article.excerpt}</p><div className="mt-8 flex flex-wrap items-center gap-4 text-xs"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#C6A15B] font-bold text-black">{article.author.initials}</span><b>{article.author.display_name}</b><span className="text-white/50">{date(article.published_at)}</span><span className="text-white/50">{article.reading_time_minutes} min read</span><span className="text-white/50">{article.view_count.toLocaleString()} views</span></div></div></header>
    <div className="mx-auto max-w-5xl px-4 py-10">{article.featured_image?.url && <figure><img src={resolveMediaUrl(article.featured_image.url)} alt={article.featured_image.alt_text || article.title} className="aspect-[16/9] w-full rounded-3xl object-cover shadow-xl" />{article.featured_image.caption && <figcaption className="mt-3 text-center text-[10px] text-[#888]">{article.featured_image.caption}</figcaption>}</figure>}<div className="mt-8 flex flex-wrap gap-2"><button onClick={async () => { await navigator.clipboard.writeText(url); setCopied(true) }} className="rounded-full border px-4 py-2 text-xs font-bold">{copied ? "Link copied" : "Copy link"}</button><a href={`https://wa.me/?text=${encodeURIComponent(`${article.title} ${url}`)}`} target="_blank" rel="noreferrer" className="rounded-full border px-4 py-2 text-xs font-bold">WhatsApp</a><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer" className="rounded-full border px-4 py-2 text-xs font-bold">Facebook</a><a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(article.title)}&url=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer" className="rounded-full border px-4 py-2 text-xs font-bold">X</a></div><div className="article-content mx-auto mt-10 max-w-3xl font-serif text-lg leading-9 [&_a]:text-[#9A762D] [&_blockquote]:border-l-4 [&_blockquote]:border-[#C6A15B] [&_blockquote]:pl-5 [&_h2]:mt-10 [&_h2]:text-3xl [&_h2]:font-bold [&_h3]:mt-8 [&_h3]:text-2xl [&_h3]:font-bold [&_li]:ml-6 [&_li]:list-disc [&_p]:mb-6" dangerouslySetInnerHTML={{ __html: article.content_html || "" }} /></div>
    {!!article.related_articles?.length && <section className="bg-[#F8F4EA] px-4 py-16"><div className="mx-auto max-w-5xl"><h2 className="font-serif text-3xl font-bold">Related Articles</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{article.related_articles.map(item => <button key={item.id} onClick={() => read(item)} className="overflow-hidden rounded-2xl border bg-white text-left">{item.featured_image?.url && <img src={resolveMediaUrl(item.featured_image.url)} alt="" className="aspect-[16/10] w-full object-cover" />}<div className="p-5"><span className="text-[10px] font-bold text-[#C6A15B]">{item.category.name}</span><h3 className="mt-2 font-serif text-lg font-bold">{item.title}</h3></div></button>)}</div></div></section>}
  </article>
}
