import { useEffect, useMemo, useState } from "react"
import type { Page } from "./App"
import BrandLogo from "./BrandLogo"
import { ApiError, Booking, BookingPrice, BookingTravellerInput, bookingApi, customerBookingApi, resolveMediaUrl, Tour, tourApi } from "./api"
import { useAuth } from "./AuthContext"

type Selection={tour_id:string;tour_slug:string;tour_title:string;package_id:string;package_name:string;departure_id:string;start_date:string;end_date:string;adults:number;children:number;price_adult:number;price_child:number;currency:string;image?:string;location:string;duration_days:number;nights?:number;available:number;capacity:number;category?:string}
const readSelection=():Selection|undefined=>{try{return JSON.parse(sessionStorage.getItem("kobani_booking_selection")||"")}catch{return undefined}}
const err=(e:unknown)=>e instanceof ApiError?e.code.replaceAll("_"," "):"The booking service is unavailable"
const countries=["Ghana","Nigeria","United Kingdom","United States","Canada","Germany","France","South Africa","Kenya","Other"]

export default function BookingPage({onNavigate}:{onNavigate:(p:Page)=>void}){
 const { user } = useAuth()
 const [selection,setSelection]=useState<Selection|undefined>(readSelection),[tour,setTour]=useState<Tour>(),[step,setStep]=useState(0),[adults,setAdults]=useState(readSelection()?.adults||1),[children,setChildren]=useState(readSelection()?.children||0),[infants,setInfants]=useState(0)
 const [contact,setContact]=useState({full_name:"",email:"",phone:"",country:"Ghana"}),[travellers,setTravellers]=useState<BookingTravellerInput[]>([]),[price,setPrice]=useState<BookingPrice>(),[booking,setBooking]=useState<Booking>(),[paymentOption,setPaymentOption]=useState("deposit"),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[seconds,setSeconds]=useState(0)
 useEffect(()=>{if(user?.role==="customer")setContact(current=>({full_name:current.full_name||user.fullName,email:user.email,phone:current.phone||`${user.phoneCountryCode}${user.phoneNumber}`,country:current.country==="Ghana"?(user.countryOfResidence||current.country):current.country}))},[user])
 useEffect(()=>{if(selection?.tour_slug)tourApi.publicDetail(selection.tour_slug).then(r=>setTour(r.data.tour)).catch(()=>setNotice("This tour is no longer available."))},[selection?.tour_slug])
 useEffect(()=>{if(!selection)return;const timer=setTimeout(()=>bookingApi.calculatePrice({tour_id:selection.tour_id,package_id:selection.package_id,departure_id:selection.departure_id,adults,children,infants,payment_option:paymentOption}).then(r=>setPrice(r.data.price)).catch(e=>{setPrice(undefined);setNotice(err(e))}),180);return()=>clearTimeout(timer)},[selection?.departure_id,selection?.package_id,adults,children,infants,paymentOption])
 useEffect(()=>{const kinds=[...Array(adults).fill("adult"),...Array(children).fill("child"),...Array(infants).fill("infant")] as ("adult"|"child"|"infant")[];setTravellers(old=>kinds.map((kind,i)=>old[i]?.traveller_type===kind?old[i]:{first_name:"",last_name:"",date_of_birth:"",nationality:"",traveller_type:kind,dietary_requirements:"",accessibility_requirements:"",special_requests:""}))},[adults,children,infants])
 useEffect(()=>{if(!booking?.reservation_expires_at)return;const update=()=>setSeconds(Math.max(0,Math.floor((new Date(booking.reservation_expires_at).getTime()-Date.now())/1000)));update();const id=setInterval(update,1000);return()=>clearInterval(id)},[booking?.reservation_expires_at])
 const selectedDeparture=tour?.departures?.find(x=>x.id===selection?.departure_id)
 const selectedPackage=tour?.packages.find(x=>x.id===selection?.package_id)
 useEffect(()=>{if(selectedPackage)setPaymentOption(selectedPackage.deposit_enabled?"deposit":"full_payment")},[selectedPackage?.id])
 const chooseDeparture=(id:string)=>{if(!tour)return;const d=tour.departures?.find(x=>x.id===id);if(!d)return;const next={...selection!,departure_id:id,start_date:d.start_date,end_date:d.end_date,available:d.available,capacity:d.capacity,price_adult:d.price};setSelection(next);sessionStorage.setItem("kobani_booking_selection",JSON.stringify(next))}
 const next=()=>{if(step===0&&(!selection||!selectedPackage||adults+children<selectedPackage.min_guests||adults+children>selectedPackage.max_guests||adults+children>selection.available)){setNotice(selectedPackage&&adults+children<selectedPackage.min_guests?`This package requires a minimum of ${selectedPackage.min_guests} travellers.`:"Choose a valid traveller count within the package and departure limits.");return}if(step===1&&(!contact.full_name.trim()||!/^\S+@\S+\.\S+$/.test(contact.email)||!contact.phone.trim())){setNotice("Enter your full name, email and phone number.");return}if(step===2&&travellers.some(x=>!x.first_name.trim()||!x.last_name.trim()||!x.nationality)){setNotice("Complete the name and nationality for every traveller.");return}setNotice("");setStep(x=>Math.min(3,x+1))}
 const reserve=async()=>{if(!selection||!price)return;setBusy(true);try{const key=sessionStorage.getItem("kobani_booking_idempotency")||crypto.randomUUID();sessionStorage.setItem("kobani_booking_idempotency",key);const payload={tour_id:selection.tour_id,package_id:selection.package_id,departure_id:selection.departure_id,adults,children,infants,payment_option:paymentOption,contact,travellers,accept_terms:true};const result=user?.role==="customer"?await customerBookingApi.create(payload,key):await bookingApi.create(payload,key);setBooking(result.data.booking);if(result.data.booking_access_token)sessionStorage.setItem("kobani_booking_access_token",result.data.booking_access_token);sessionStorage.setItem("kobani_active_booking_id",result.data.booking.id);setNotice("Your places are reserved. Complete payment before the countdown ends.")}catch(e){setNotice(err(e))}finally{setBusy(false)}}
 const pay=async()=>{if(!booking)return;setBusy(true);setNotice("Preparing secure Paystack checkout…");try{const result=user?.role==="customer"?await customerBookingApi.initializePayment(booking.id,paymentOption as "deposit"|"full_payment"):await bookingApi.initializePaystack(booking.id,paymentOption);sessionStorage.setItem("kobani_payment_reference",result.data.payment_reference);sessionStorage.setItem("kobani_active_booking_id",booking.id);const w=window as Window & {PaystackPop?:new()=>{resumeTransaction:(code:string)=>void}};if(!w.PaystackPop){await new Promise<void>((resolve,reject)=>{const script=document.createElement("script");script.src="https://js.paystack.co/v2/inline.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("PAYSTACK_SCRIPT_FAILED"));document.head.appendChild(script)})}if(w.PaystackPop)new w.PaystackPop().resumeTransaction(result.data.access_code);else window.location.assign(result.data.authorization_url)}catch(e){setNotice(err(e));setBusy(false)}}
 const totalPeople=adults+children+infants,input="w-full h-12 rounded-xl border border-[#DED6C8] px-4 text-sm outline-none focus:border-[#C6A15B]"
 if(!selection)return <div className="min-h-screen bg-[#F8F4EA] grid place-items-center p-5 text-center"><div><BrandLogo className="w-16 h-16 mx-auto"/><h1 className="font-serif text-4xl font-bold mt-5">Select a journey first</h1><p className="text-[#777] mt-2">Booking must begin from a live tour and available departure.</p><button onClick={()=>onNavigate("tours")} className="bg-[#C6A15B] px-6 py-3 rounded-xl font-bold mt-6">Browse tours</button></div></div>
 return <div className="min-h-screen bg-[#F8F4EA] text-[#171717]"><header className="bg-[#0B0B0B] text-white px-4 py-5"><div className="max-w-6xl mx-auto flex items-center"><BrandLogo className="w-10 h-10"/><div className="ml-3"><b className="font-serif text-xl">KOBANI</b><p className="text-[9px] text-white/40">SECURE BOOKING</p></div><div className="ml-auto flex items-center gap-3">{user?.role==="customer"&&<button onClick={()=>onNavigate("dashboard")} className="rounded-xl border border-white/20 px-3 py-2 text-xs font-semibold text-white/80 hover:border-[#C6A15B] hover:text-[#C6A15B] sm:px-4">← Back to Dashboard</button>}{booking&&<div className={`hidden text-sm sm:block ${seconds<180?"text-red-300":"text-[#D6B873]"}`}>Reservation {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,"0")}</div>}</div></div></header>
 <div className="bg-white border-b"><div className="max-w-4xl mx-auto px-4 py-5 flex">{["Tour & travellers","Contact","Traveller details","Review & payment"].map((x,i)=><div key={x} className="flex-1 flex items-center"><span className={`w-8 h-8 rounded-full grid place-items-center text-xs font-bold ${i<=step?"bg-[#C6A15B]":"bg-[#EEE9DF] text-[#999]"}`}>{i<step?"✓":i+1}</span><span className="hidden md:block text-xs ml-2">{x}</span>{i<3&&<span className="h-px bg-[#DED6C8] flex-1 mx-3"/>}</div>)}</div></div>
 {notice&&<button onClick={()=>setNotice("")} className="fixed top-5 left-1/2 -translate-x-1/2 z-50 bg-white border shadow-xl px-5 py-3 rounded-xl text-xs max-w-[90vw]">{notice}</button>}
 <main className="max-w-6xl mx-auto p-4 sm:p-8 grid lg:grid-cols-[1fr_340px] gap-6"><section className="bg-white border rounded-3xl p-5 sm:p-8">
 {step===0&&<div><p className="text-[10px] tracking-[.2em] font-bold text-[#B88B39]">STEP 1</p><h1 className="font-serif text-3xl font-bold mt-2">Departure and travellers</h1><label className="block mt-6"><span className="text-xs font-bold">Available departure</span><select className={`${input} mt-2`} value={selection.departure_id} onChange={e=>chooseDeparture(e.target.value)}>{tour?.departures?.filter(x=>x.available>0&&["open","limited"].includes(x.status)).map(x=><option value={x.id} key={x.id}>{x.start_date} to {x.end_date} · {x.available} places · {x.currency} {x.price}</option>)}</select></label><div className="grid sm:grid-cols-3 gap-4 mt-6">{[["Adults",adults,setAdults,1],["Children",children,setChildren,0],["Infants",infants,setInfants,0]].map(([label,value,setter,min])=><label key={String(label)}><span className="text-xs font-bold">{label as string}</span><input type="number" min={min as number} max={selection.available} value={value as number} onChange={e=>(setter as (v:number)=>void)(Math.max(min as number,+e.target.value))} className={`${input} mt-2`}/></label>)}</div><div className="bg-[#F8F4EA] rounded-2xl p-4 mt-6 text-sm flex justify-between"><span>Requested spaces</span><b>{adults+children} of {selection.available} available</b></div></div>}
 {step===1&&<div><p className="text-[10px] tracking-[.2em] font-bold text-[#B88B39]">STEP 2</p><h1 className="font-serif text-3xl font-bold mt-2">Your contact details</h1><p className="text-sm text-[#777] mt-2">We’ll send your booking confirmation and receipt here.</p><div className="grid sm:grid-cols-2 gap-4 mt-6">{[["Full name","full_name","text"],["Email address","email","email"],["Phone number","phone","tel"]].map(([label,key,type])=><label key={key}><span className="text-xs font-bold">{label}</span><input type={type} value={contact[key as keyof typeof contact]} onChange={e=>setContact(x=>({...x,[key]:e.target.value}))} className={`${input} mt-2`} autoComplete={key==="email"?"email":key==="full_name"?"name":"tel"}/></label>)}<label><span className="text-xs font-bold">Country</span><select className={`${input} mt-2`} value={contact.country} onChange={e=>setContact(x=>({...x,country:e.target.value}))}>{countries.map(x=><option key={x}>{x}</option>)}</select></label></div></div>}
 {step===2&&<div><p className="text-[10px] tracking-[.2em] font-bold text-[#B88B39]">STEP 3</p><h1 className="font-serif text-3xl font-bold mt-2">Traveller information</h1><p className="text-sm text-[#777] mt-2">Passport information is not required for this booking.</p><div className="space-y-4 mt-6">{travellers.map((person,i)=><article key={i} className="border rounded-2xl p-4"><div className="flex justify-between"><b className="font-serif text-lg">{i===0?"Lead traveller":`${person.traveller_type} ${i+1}`}</b><span className="text-xs uppercase text-[#B88B39]">{person.traveller_type}</span></div><div className="grid sm:grid-cols-2 gap-3 mt-4">{[["First name","first_name","text"],["Last name","last_name","text"],["Date of birth","date_of_birth","date"],["Nationality","nationality","text"],["Dietary requirements","dietary_requirements","text"],["Accessibility requirements","accessibility_requirements","text"]].map(([label,key,type])=><label key={key}><span className="text-[10px] uppercase text-[#777]">{label}</span><input type={type} value={String(person[key as keyof BookingTravellerInput]||"")} onChange={e=>setTravellers(x=>x.map((p,n)=>n===i?{...p,[key]:e.target.value}:p))} className={`${input} mt-1`}/></label>)}</div></article>)}</div></div>}
 {step===3&&<div><p className="text-[10px] tracking-[.2em] font-bold text-[#B88B39]">FINAL STEP</p><h1 className="font-serif text-3xl font-bold mt-2">Review and secure payment</h1><div className="border rounded-2xl overflow-hidden mt-6"><div className="p-5 bg-[#F8F4EA]"><b>{selection.tour_title}</b><p className="text-sm text-[#777]">{selection.start_date} to {selection.end_date} · {totalPeople} travellers</p></div><div className="p-5 space-y-3 text-sm"><div className="flex justify-between"><span>Adults × {adults}</span><b>{price?.currency} {price?.adult_unit}</b></div>{children>0&&<div className="flex justify-between"><span>Children × {children}</span><b>{price?.currency} {price?.child_unit}</b></div>}<div className="border-t pt-3 flex justify-between text-lg"><b>Total</b><b>{price?.currency} {price?.total}</b></div></div></div><div className="grid sm:grid-cols-2 gap-3 mt-5">{[["deposit",`Pay ${price?.deposit_percent}% deposit`,price?.deposit],["full_payment","Pay in full",price?.total]].map(([value,label,amount])=><label key={value} className={`border-2 rounded-2xl p-4 cursor-pointer ${paymentOption===value?"border-[#C6A15B] bg-[#C6A15B]/5":"border-[#DED6C8]"}`}><input type="radio" className="mr-2" checked={paymentOption===value} onChange={()=>setPaymentOption(value||"deposit")}/><b className="text-sm">{label}</b><span className="block font-serif text-2xl font-bold mt-2">{price?.currency} {amount}</span></label>)}</div><label className="flex gap-3 text-xs text-[#666] mt-5"><input type="checkbox" checked readOnly/>I agree to the booking terms and cancellation policy.</label>{!booking?<button disabled={busy||!price} onClick={reserve} className="w-full bg-[#C6A15B] disabled:bg-gray-200 rounded-xl py-4 font-bold mt-6">{busy?"Reserving places…":"Reserve places and continue"}</button>:<div className="mt-6"><div className="bg-green-50 border border-green-200 rounded-xl p-4 text-sm text-green-800">Reservation {booking.booking_reference} created. Your server-calculated amount is locked until the countdown expires.</div><button disabled={busy||seconds===0} onClick={pay} className="w-full bg-[#0B0B0B] text-white disabled:bg-gray-300 rounded-xl py-4 font-bold mt-3">{busy?"Opening Paystack…":`Pay securely with Paystack · ${price?.currency} ${paymentOption==="deposit"?price?.deposit:price?.total}`}</button><p className="text-xs text-center text-[#888] mt-3">KOBANI never receives or stores your card details.</p></div>}</div>}
 <div className="flex justify-between mt-8 pt-5 border-t"><button disabled={step===0||!!booking} onClick={()=>setStep(x=>x-1)} className="border rounded-xl px-5 py-3 text-sm disabled:opacity-30">Back</button>{step<3&&<button onClick={next} className="bg-[#C6A15B] rounded-xl px-6 py-3 text-sm font-bold">Continue</button>}</div></section>
 <aside><div className="bg-[#111] text-white rounded-3xl overflow-hidden sticky top-5">{selection.image&&<img src={resolveMediaUrl(selection.image)} alt="" className="w-full h-44 object-cover"/>}<div className="p-6"><p className="text-[#C6A15B] text-[10px] tracking-[.2em]">{selection.category}</p><h2 className="font-serif text-2xl font-bold mt-2">{selection.tour_title}</h2><p className="text-white/50 text-sm mt-2">{selection.location}</p><div className="border-t border-white/10 mt-5 pt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-white/50">Departure</span><b>{selectedDeparture?.start_date||selection.start_date}</b></div><div className="flex justify-between"><span className="text-white/50">Duration</span><b>{selection.duration_days} days</b></div><div className="flex justify-between"><span className="text-white/50">Travellers</span><b>{totalPeople}</b></div>{price&&<div className="flex justify-between border-t border-white/10 pt-3"><span>Total</span><b className="text-[#C6A15B]">{price.currency} {price.total}</b></div>}</div></div></div></aside></main></div>
}
