import { useState } from "react"
import type { Page } from "./App"
import { ApiError, customerBookingApi, resolveMediaUrl } from "./api"

type Selection={id:string;title:string;slug:string;location:string;flyer?:string}
export default function BookingRequestPage({onNavigate}:{onNavigate:(page:Page)=>void}){
  const selection=(()=>{try{return JSON.parse(sessionStorage.getItem("kobani_booking_request_tour")||"") as Selection}catch{return null}})()
  const [details,setDetails]=useState(""),[preferredDate,setPreferredDate]=useState(""),[travellers,setTravellers]=useState(""),[notes,setNotes]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[reference,setReference]=useState("")
  if(!selection)return <main className="grid min-h-screen place-items-center bg-[#F8F4EA] p-6 text-center"><div><h1 className="font-serif text-3xl font-bold">Choose a tour first</h1><button className="admin-gold mt-5" onClick={()=>onNavigate("tours")}>Browse Tours</button></div></main>
  const submit=async()=>{if(!details.trim()){setError("Package / Booking Details is required.");return}setBusy(true);setError("");try{const key=crypto.randomUUID();const result=await customerBookingApi.createRequest({tour_id:selection.id,request_details:details,preferred_date:preferredDate,traveller_count:travellers?Number(travellers):undefined,special_requests:notes},key);sessionStorage.setItem("kobani:selected-booking-id",result.data.booking.id);setReference(result.data.booking.booking_reference)}catch(reason){setError(reason instanceof ApiError?reason.code.replaceAll("_"," "):"Unable to submit your booking request. Please try again.")}finally{setBusy(false)}}
  if(reference)return <main className="grid min-h-screen place-items-center bg-[#F8F4EA] p-6"><section className="max-w-xl rounded-3xl border bg-white p-8 text-center"><p className="eyebrow">Request received</p><h1 className="mt-3 font-serif text-4xl font-bold">Booking Request Received</h1><p className="mt-4 font-bold">{reference}</p><p className="mt-4 text-sm leading-6 text-[#6F6B63]">KOBANI will review your request and respond through your account.</p><div className="mt-7 flex justify-center gap-3"><button className="admin-gold" onClick={()=>onNavigate("customer-booking-detail")}>View Booking</button><button className="admin-outline" onClick={()=>onNavigate("tours")}>Browse More Tours</button></div></section></main>
  return <main className="min-h-screen bg-[#F8F4EA] p-4 py-10"><div className="mx-auto grid max-w-5xl gap-7 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border bg-white p-6 sm:p-8"><p className="eyebrow">Booking request</p><h1 className="mt-2 font-serif text-4xl font-bold">Tell us what you need</h1><div className="mt-6 rounded-xl bg-[#F8F4EA] p-4"><small>Tour</small><b className="block font-serif text-xl">{selection.title}</b><span className="text-xs text-[#777]">{selection.location}</span></div><label className="form-field mt-6"><span>Package / Booking Details *</span><small>Tell us which package or experience you are interested in and any important booking details.</small><textarea className="admin-input mt-2 min-h-44 w-full" value={details} onChange={e=>setDetails(e.target.value)} placeholder="I am interested in the Heritage Executive package for 2 travellers…"/></label><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="form-field"><span>Preferred travel date</span><input type="date" className="admin-input w-full" value={preferredDate} onChange={e=>setPreferredDate(e.target.value)}/></label><label className="form-field"><span>Number of travellers</span><input type="number" min="1" max="500" className="admin-input w-full" value={travellers} onChange={e=>setTravellers(e.target.value)}/></label></div><label className="form-field mt-5"><span>Additional notes / special requests</span><textarea className="admin-input min-h-28 w-full" value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} onClick={()=>void submit()} className="admin-gold mt-6 w-full disabled:opacity-50">{busy?"Submitting…":"Submit Booking Request"}</button></section><aside>{selection.flyer&&<img src={resolveMediaUrl(selection.flyer)} alt={`${selection.title} flyer`} className="sticky top-5 max-h-[760px] w-full rounded-2xl border bg-black object-contain p-2"/>}</aside></div></main>
}
