import { useEffect, useMemo, useState } from "react"
import type { Page } from "./App"
import CustomerPortalLayout from "./CustomerPortalLayout"
import { customerProductOrderApi, type CustomerProductOrder } from "./api"

const labels: Record<string, string> = { pending: "Pending", new: "New", processing: "Processing", shipped: "Shipped", delivered: "Delivered", cancelled: "Cancelled" }
const money = (minor: number, currency: string) => new Intl.NumberFormat(undefined, { style: "currency", currency: currency || "USD" }).format(minor / 100)
const date = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "—"

export default function CustomerProductOrdersPage({ onNavigate }: { onNavigate: (page: Page) => void }) {
  const [orders, setOrders] = useState<CustomerProductOrder[]>([]), [filter, setFilter] = useState("all"), [selected, setSelected] = useState<CustomerProductOrder | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("")
  useEffect(() => { customerProductOrderApi.list().then(result => setOrders(result.data.orders)).catch(error => setError(error instanceof Error ? error.message : "Could not load your orders")).finally(() => setLoading(false)) }, [])
  const shown = useMemo(() => filter === "all" ? orders : orders.filter(order => order.status === filter), [orders, filter])
  return <CustomerPortalLayout title="Product Orders" subtitle="Track your African Market purchases." active="Product Orders" onNavigate={onNavigate}><main className="mx-auto max-w-[1200px] p-4 sm:p-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#C6A15B]">African Market</p><h2 className="mt-1 font-serif text-3xl font-bold">Your Orders</h2><p className="mt-1 text-xs text-[#6F6B63]">Only orders placed from your account appear here.</p></div><button onClick={()=>onNavigate("market")} className="rounded-xl bg-[#0B0B0B] px-5 py-3 text-xs font-bold text-white">Continue Shopping</button></div>
    {orders.length>0&&<div className="mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-[#E6DFD2] bg-white p-2">{["all","pending","processing","shipped","delivered","cancelled"].map(value=><button key={value} onClick={()=>setFilter(value)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-bold ${filter===value?"bg-[#0B0B0B] text-white":"text-[#777]"}`}>{value==="all"?"All":labels[value]} <span className="ml-1 opacity-60">{value==="all"?orders.length:orders.filter(order=>order.status===value).length}</span></button>)}</div>}
    {error&&<div role="alert" className="mt-6 rounded-xl bg-[#C84A4A]/10 p-4 text-xs text-[#C84A4A]">{error}</div>}
    {loading?<div className="py-24 text-center text-sm text-[#777]">Loading your product orders…</div>:shown.length===0?<section className="mt-6 rounded-2xl border border-[#E6DFD2] bg-white p-12 text-center"><div className="text-4xl">◻</div><h3 className="mt-4 font-serif text-2xl font-bold">{orders.length?"No matching orders":"No product orders yet"}</h3><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-[#777]">{orders.length?"Choose another status to see your orders.":"When you complete a purchase from the African Market, the real order and its delivery updates will appear here."}</p>{!orders.length&&<button onClick={()=>onNavigate("market")} className="mt-5 rounded-xl bg-[#C6A15B] px-5 py-3 text-xs font-bold">Explore the Market</button>}</section>:<section className="mt-6 space-y-4">{shown.map(order=><article key={order.id} className="overflow-hidden rounded-2xl border border-[#E6DFD2] bg-white"><div className="flex flex-wrap items-center gap-5 border-b border-[#EEE8DD] bg-[#FFFDF8] px-5 py-4"><div><p className="text-[9px] uppercase text-[#999]">Order reference</p><b className="font-serif">{order.reference}</b></div><div><p className="text-[9px] uppercase text-[#999]">Order date</p><b className="text-xs">{date(order.created_at)}</b></div><span className="ml-auto rounded-full bg-[#C6A15B]/15 px-3 py-1 text-[9px] font-bold text-[#8B6A2D]">{labels[order.status]||order.status}</span></div><div className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center"><div className="flex -space-x-3">{order.items.slice(0,4).map((item,index)=><div key={`${item.name}-${index}`} className="grid h-16 w-16 place-items-center overflow-hidden rounded-xl border-2 border-white bg-[#F3EEE5]">{item.image?<img src={item.image} alt={item.name} className="h-full w-full object-cover"/>:<span className="text-xl">◻</span>}</div>)}</div><div className="min-w-0 flex-1"><b className="font-serif">{order.items[0]?.name||"Order items"}{order.items.length>1&&` + ${order.items.length-1} more`}</b><p className="mt-1 text-[10px] text-[#999]">{order.items.reduce((sum,item)=>sum+item.quantity,0)} item(s) · Payment {order.payment_status}</p>{order.tracking_number&&<p className="mt-2 text-[10px] text-[#6F6B63]">Tracking: <b>{order.tracking_number}</b></p>}</div><div><p className="text-[9px] uppercase text-[#999]">Order total</p><b className="font-serif text-xl">{money(order.total_minor,order.currency)}</b></div><button onClick={()=>setSelected(order)} className="rounded-xl bg-[#0B0B0B] px-4 py-3 text-xs font-bold text-white">View Details</button></div></article>)}</section>}
    {selected&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/60 p-4" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><div className="max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white"><div className="flex items-center justify-between bg-[#0B0B0B] p-5 text-white"><div><p className="text-[9px] uppercase tracking-wider text-[#C6A15B]">Order details</p><h3 className="font-serif text-xl font-bold">{selected.reference}</h3></div><button onClick={()=>setSelected(null)} aria-label="Close">✕</button></div><div className="space-y-4 p-6">{selected.items.map((item,index)=><div key={`${item.name}-${index}`} className="flex items-center gap-3"><div className="grid h-14 w-14 place-items-center overflow-hidden rounded-xl bg-[#F3EEE5]">{item.image?<img src={item.image} alt={item.name} className="h-full w-full object-cover"/>:"◻"}</div><div className="flex-1"><b className="text-xs">{item.name}</b><p className="text-[10px] text-[#999]">{item.variant||"Standard"} · Qty {item.quantity}</p></div><b className="text-xs">{money(item.unit_price_minor*item.quantity,selected.currency)}</b></div>)}<div className="flex justify-between border-t pt-4"><span className="text-xs text-[#777]">Total</span><b className="font-serif text-xl">{money(selected.total_minor,selected.currency)}</b></div>{selected.tracking_url&&<a href={selected.tracking_url} target="_blank" rel="noreferrer" className="block rounded-xl bg-[#C6A15B] py-3 text-center text-xs font-bold">Track Order</a>}</div></div></div>}
  </main></CustomerPortalLayout>
}
