import { useEffect, useState } from "react"
import type { Page } from "./App"
import { ApiError, customerAccountApi, type CustomerAccount } from "./api"
import { useAuth } from "./AuthContext"
import CustomerPortalLayout from "./CustomerPortalLayout"

const input="h-11 w-full rounded-xl border border-[#E2DBCE] px-3.5 text-sm outline-none disabled:border-transparent disabled:bg-[#FAF8F3] focus:border-[#C6A15B]"
const Field=({label,children}:{label:string;children:React.ReactNode})=><label><span className="mb-1.5 block text-[10px] uppercase tracking-wider text-[#9A9590]">{label}</span>{children}</label>
const Card=({title,children}:{title:string;children:React.ReactNode})=><section className="rounded-2xl border border-[#E6DFD2] bg-white p-5 sm:p-6"><h2 className="mb-5 font-serif text-lg font-bold">{title}</h2>{children}</section>

export default function CustomerProfilePage({onNavigate}:{onNavigate:(page:Page)=>void}){
 const {refreshUser}=useAuth();const [account,setAccount]=useState<CustomerAccount>(),[form,setForm]=useState<Record<string,string>>({}),[editing,setEditing]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("")
 const fill=(data:CustomerAccount)=>setForm({full_name:data.user.fullName,phone_country_code:data.user.phoneCountryCode||"",phone_number:data.user.phoneNumber||"",country_of_residence:data.user.countryOfResidence||"",date_of_birth:data.profile.date_of_birth||"",gender:data.profile.gender||"",address:data.profile.address||"",city:data.profile.city||"",nationality:data.profile.nationality||"",emergency_name:data.profile.emergency_name||"",emergency_phone:data.profile.emergency_phone||"",emergency_relationship:data.profile.emergency_relationship||""})
 useEffect(()=>{customerAccountApi.get().then(result=>{setAccount(result.data);fill(result.data)}).catch(()=>setError("Your profile could not be loaded.")).finally(()=>setLoading(false))},[])
 const set=(key:string,value:string)=>setForm(data=>({...data,[key]:value}))
 const save=async()=>{setSaving(true);setError("");try{const result=await customerAccountApi.updateProfile(form);setAccount(result.data);fill(result.data);setEditing(false);setNotice("Your profile changes have been saved securely.");await refreshUser()}catch(e){setError(e instanceof ApiError?e.code.replaceAll("_"," "):"Your profile could not be saved.")}finally{setSaving(false)}}
 const cancel=()=>{if(account)fill(account);setEditing(false);setError("")}
 return <CustomerPortalLayout title="My Profile" subtitle="Manage your verified personal and travel details." active="Profile" onNavigate={onNavigate}><main className="mx-auto max-w-[1150px] p-4 sm:p-7">{notice&&<div className="mb-5 rounded-xl border border-[#27855C]/20 bg-[#27855C]/10 px-4 py-3 text-xs text-[#27855C]">✓ {notice}</div>}{error&&<div role="alert" className="mb-5 rounded-xl border border-[#C84A4A]/20 bg-[#C84A4A]/10 px-4 py-3 text-xs text-[#C84A4A]">{error}</div>}{loading?<div className="py-24 text-center text-sm text-[#6F6B63]">Loading your profile…</div>:account&&<><section className="relative flex flex-col gap-5 overflow-hidden rounded-2xl bg-[#0B0B0B] p-5 text-white sm:flex-row sm:items-center sm:p-7"><span className="grid h-24 w-24 place-items-center rounded-full border-4 border-[#C6A15B]/30 bg-[#C6A15B] font-serif text-3xl font-bold text-black">{account.user.fullName.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase()}</span><div className="flex-1"><p className="text-[9px] uppercase tracking-[.18em] text-[#C6A15B]">Explorer Member</p><h2 className="mt-1 font-serif text-2xl font-bold">{account.user.fullName}</h2><p className="mt-1 text-xs text-[#999]">{account.user.email} · {account.user.countryOfResidence||"Location not added"}</p><span className="mt-4 inline-block rounded-full bg-[#27855C]/15 px-2.5 py-1 text-[9px] font-bold text-[#6DD3A5]">EMAIL VERIFIED</span></div><div className="flex gap-2">{editing?<><button onClick={cancel} className="rounded-xl border border-white/20 px-4 py-2.5 text-xs font-bold">Cancel</button><button disabled={saving} onClick={()=>void save()} className="rounded-xl bg-[#C6A15B] px-4 py-2.5 text-xs font-bold text-black disabled:opacity-60">{saving?"Saving…":"Save Changes"}</button></>:<button onClick={()=>setEditing(true)} className="rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-black">Edit Profile</button>}</div></section>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card title="Personal information"><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Full name"><input disabled={!editing} value={form.full_name} onChange={e=>set("full_name",e.target.value)} className={input}/></Field></div><Field label="Date of birth"><input disabled={!editing} type="date" value={form.date_of_birth} onChange={e=>set("date_of_birth",e.target.value)} className={input}/></Field><Field label="Gender"><select disabled={!editing} value={form.gender} onChange={e=>set("gender",e.target.value)} className={input}><option value="">Not specified</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></Field><Field label="Nationality"><input disabled={!editing} value={form.nationality} onChange={e=>set("nationality",e.target.value)} className={input}/></Field><Field label="Country of residence"><input disabled={!editing} value={form.country_of_residence} onChange={e=>set("country_of_residence",e.target.value)} className={input}/></Field></div></Card>
 <Card title="Contact information"><div className="space-y-4"><Field label="Verified email address"><input disabled value={account.user.email} className={input}/></Field><div className="grid gap-4 sm:grid-cols-[110px_1fr]"><Field label="Country code"><input disabled={!editing} value={form.phone_country_code} onChange={e=>set("phone_country_code",e.target.value)} className={input} placeholder="+233"/></Field><Field label="Phone number"><input disabled={!editing} value={form.phone_number} onChange={e=>set("phone_number",e.target.value)} className={input}/></Field></div><Field label="Street address"><input disabled={!editing} value={form.address} onChange={e=>set("address",e.target.value)} className={input}/></Field><Field label="City"><input disabled={!editing} value={form.city} onChange={e=>set("city",e.target.value)} className={input}/></Field></div></Card>
 <div className="lg:col-span-2"><Card title="Emergency contact"><div className="grid gap-4 sm:grid-cols-3"><Field label="Full name"><input disabled={!editing} value={form.emergency_name} onChange={e=>set("emergency_name",e.target.value)} className={input}/></Field><Field label="Relationship"><input disabled={!editing} value={form.emergency_relationship} onChange={e=>set("emergency_relationship",e.target.value)} className={input}/></Field><Field label="Phone number"><input disabled={!editing} value={form.emergency_phone} onChange={e=>set("emergency_phone",e.target.value)} className={input}/></Field></div><p className="mt-4 text-[10px] text-[#9A9590]">Used only when assistance is required during an active journey.</p></Card></div></div></>}</main></CustomerPortalLayout>
}
