import { useEffect, useState } from "react"
import type { Page } from "./App"
import { customerBookingApi, type Booking } from "./api"
import CustomerPortalLayout from "./CustomerPortalLayout"
const money=(booking:Booking,minor=booking.total_minor)=>new Intl.NumberFormat(undefined,{style:"currency",currency:booking.currency}).format(minor/100)
export default function CustomerBookingsPage({onNavigate}:{onNavigate:(page:Page)=>void}){
  const [items,setItems]=useState<Booking[]>([]),[loading,setLoading]=useState(true)
  useEffect(()=>{customerBookingApi.list().then(result=>setItems(result.data.bookings)).finally(()=>setLoading(false))},[])
  const open=(booking:Booking)=>{sessionStorage.setItem("kobani:selected-booking-id",booking.id);onNavigate("customer-booking-detail")}
  return <CustomerPortalLayout title="My Bookings" subtitle="Your requests, conversations, invoices and confirmed journeys" active="My Bookings" onNavigate={onNavigate}><main className="p-4 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your journeys</p><h1 className="page-title">My Bookings</h1></div><button onClick={()=>onNavigate("tours")} className="admin-gold">Explore Tours</button></div><div className="mt-6 space-y-5">{items.map(booking=><article className="rounded-2xl border bg-white p-5" key={booking.id}><div className="flex flex-wrap justify-between gap-4"><div><small>{booking.booking_reference}</small><h2 className="font-serif text-2xl font-bold">{booking.tour.title}</h2><p className="mt-1 text-sm text-[#777]">{booking.workflow==="flyer_request"?(booking.preferred_date?`Preferred date: ${booking.preferred_date}`:"Flexible travel date"):`${booking.departure.start_date} · ${booking.traveller_summary.spaces} travellers`}</p></div><div className="text-right"><span className="pill warning capitalize">{booking.booking_status.replaceAll("_"," ")}</span><p className="mt-2 text-xs capitalize text-[#777]">{booking.payment_status.replaceAll("_"," ")}</p>{booking.balance_minor>0&&<b className="mt-2 block text-[#A36D20]">{money(booking,booking.balance_minor)} due</b>}</div></div>{booking.workflow==="flyer_request"&&<p className="mt-4 line-clamp-2 text-sm text-[#666]">{booking.request_details}</p>}<button className="admin-black mt-5" onClick={()=>open(booking)}>View Booking</button></article>)}{loading&&<div className="py-20 text-center">Loading bookings…</div>}{!loading&&!items.length&&<div className="rounded-2xl border bg-white p-16 text-center"><h2 className="font-serif text-2xl font-bold">No bookings yet</h2><button onClick={()=>onNavigate("tours")} className="admin-gold mt-5">Browse Tours</button></div>}</div></main></CustomerPortalLayout>
}
