import { COMPANY } from "./companyProfile"
import { LEGAL_VERSIONS } from "./config/legal"
import type { Page } from "./App"

type LegalKind = "privacy" | "terms" | "refund" | "cancellation" | "cookies"
type Section = [string, React.ReactNode]

const policyLink = (page: Page, label: string, onNavigate: (page: Page) => void) => (
  <button className="font-semibold text-[#9A7636] underline underline-offset-2" onClick={() => onNavigate(page)}>{label}</button>
)

const privacy: Section[] = [
  ["About this policy", "This policy explains how THE KOBANI HISTORICAL AND LUXURY TOURS, trading as KOBANI, collects, uses, stores, shares and protects personal information when you use our website, create an account, enquire, book a tour, purchase a product or otherwise use our services."],
  ["Who we are", <>KOBANI is based in {COMPANY.location}. Contact us at <a className="text-[#9A7636] underline" href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a> or <a className="text-[#9A7636] underline" href={`tel:${COMPANY.phones[0]}`}>+233 24 471 9176</a>.</>],
  ["Information we collect", "We may collect account and contact details, email-verification and legal-acceptance records, booking and traveller information, payment references and status, support communications, preferences, and proportionate technical and security information. Sensitive travel information is requested only where genuinely necessary."],
  ["How and why we use information", "We use information to create and secure accounts, verify email addresses, respond to enquiries, fulfil bookings and purchases, process payments, support travellers, prevent fraud, meet legal duties and improve our services. Optional marketing is based on consent and may be withdrawn."],
  ["Lawful bases", "Depending on the activity, processing may be necessary to perform a contract, take requested pre-contract steps, comply with law, pursue legitimate business interests, protect vital interests in an emergency, or act with consent."],
  ["Cookies and account security", "We use essential authentication and security cookies and may remember language preferences. Passwords are stored as secure hashes and verification codes expire. KOBANI will never ask you to send your password or verification code by email."],
  ["Payments and sharing", "Payment providers process payment information under their own policies. We may share necessary information with hotels, transport providers, guides, attractions, technology providers, professional advisers and authorities where legally required. We do not sell personal information."],
  ["International transfers and retention", "Tour operations and technology providers may require processing outside Ghana. We use reasonable safeguards where required. Records are retained only as needed for service delivery, account operation, legal and accounting obligations, disputes, fraud prevention and security."],
  ["Your rights", "Subject to applicable law, you may request access or correction, object to or restrict certain processing, request deletion where applicable, withdraw consent, opt out of marketing, and complain to the appropriate authority. We may verify identity before fulfilling a request."],
  ["Children and educational tours", "Arrangements for minors should be made by a parent, guardian, school or authorised institution. Information about minors is collected only when necessary, with appropriate permission or authority."],
  ["Security, changes and complaints", "No transmission or storage method is completely secure, but we use reasonable safeguards. We investigate suspected breaches and notify where required. We may update this policy and will change the effective date or seek fresh consent where legally required."],
]

const terms = (onNavigate: (page: Page) => void): Section[] => [
  ["Introduction", "These Terms govern access to the KOBANI website, customer portal, enquiries, bookings, educational tours, purchases and related travel services. By creating an account, making a booking or using our services, you agree to these Terms."],
  ["Eligibility and accounts", "You must be legally able to enter the relevant agreement or act with proper authority. Account information must be accurate and credentials kept confidential. We may suspend accounts affected by fraud, misuse or serious breach."],
  ["Bookings and prices", "A request is not confirmed until KOBANI issues confirmation and any required payment is received. Availability, itinerary, inclusions, currency, taxes and payment schedule will be shown in the applicable booking information. Obvious pricing errors may be corrected before confirmation."],
  ["Payments, cancellations and refunds", <>Payment-provider terms may apply. Eligibility depends on the booking terms communicated for the specific tour or service. Review our {policyLink("refund-policy", "Refund Policy", onNavigate)} and {policyLink("cancellation-policy", "Cancellation Policy", onNavigate)} before booking.</>],
  ["Changes and force majeure", "Itineraries or suppliers may change for safety, operational reasons or events beyond reasonable control, including severe weather, public-health restrictions, civil unrest, government action, border closures, strikes or transport disruption. We will communicate material changes and provide lawful remedies where applicable."],
  ["Travel documents, health and insurance", "Travellers are responsible for passports, visas, permits and entry requirements. Relevant mobility, dietary and medical needs should be communicated when necessary. Appropriate travel insurance is strongly recommended unless confirmed booking terms state otherwise."],
  ["Conduct and heritage responsibility", "Travellers must not harass others, act illegally, endanger people, damage property or disrespect communities, sacred sites, memorials or cultural rules. Guide instructions and photography restrictions must be followed."],
  ["Suppliers, baggage and photography", "Independent accommodation, transport and destination suppliers may have additional rules. Customers should secure valuables and report loss promptly. Identifiable customer images will not be treated as automatically licensed for marketing merely because an account was created."],
  ["Privacy and acceptable use", <>Our {policyLink("privacy-policy", "Privacy Policy", onNavigate)} explains how personal information is handled. Fraud, malware, unauthorised access, false bookings and interference with the service are prohibited.</>],
  ["Availability, liability and termination", "Continuous website access is not guaranteed. Travel involves inherent risks and weather or wildlife cannot be guaranteed. Any limitation of liability is subject to Ghanaian law and does not exclude liability that cannot lawfully be excluded."],
  ["Complaints and governing law", <>Send complaints with relevant booking details to <a className="text-[#9A7636] underline" href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a>. These Terms are governed by the laws of Ghana, subject to mandatory consumer rights.</>],
  ["Changes and general provisions", "Material updates may require renewed acceptance. Confirmed bookings ordinarily remain subject to the terms accepted at booking unless lawfully agreed otherwise. Invalid provisions are severed without affecting the remainder."],
]

const refund: Section[] = [
  ["Scope", "This policy applies to refund requests relating to KOBANI tour bookings and associated travel services. Product purchases may have separate terms shown during checkout."],
  ["Deposits and full payments", "A deposit secures arrangements and may be committed to suppliers. Refund eligibility and applicable deductions depend on the cancellation terms communicated for the specific tour or service at the time of booking. The same principle applies to full payments."],
  ["Customer cancellations and rescheduling", "Contact KOBANI as soon as possible if you need to cancel or request new dates. Rescheduling is subject to availability, supplier approval and any price difference or cost already incurred. A request is not effective until KOBANI acknowledges it."],
  ["No-shows, missed departures and late arrival", "Failure to attend or arrive in time may make services non-refundable where accommodation, transport, guides, tickets or other arrangements have already been reserved. We will review the circumstances and applicable booking and supplier terms."],
  ["Third-party and non-refundable costs", "Accommodation, transport, attraction tickets, permits and other third-party charges may be non-refundable or subject to supplier deductions. Reasonable payment-provider or administrative charges may also apply where disclosed or unavoidable."],
  ["Cancellation by KOBANI", "If KOBANI cancels a service and cannot provide a suitable alternative, we will explain the available remedy, which may include rescheduling, service credit or a refund of eligible amounts. Third-party amounts remain subject to supplier terms and applicable law."],
  ["Extraordinary circumstances", "Weather, public-health events, government restrictions, transport disruption, civil unrest and other events outside reasonable control may require changes or cancellation. We will communicate available alternatives and determine refund eligibility under the booking terms, supplier commitments and applicable law."],
  ["Refund processing", "Approved refunds are returned using an appropriate available method. KOBANI will confirm the approved amount and documented deductions. Bank, card-network, mobile-money or payment-provider processing times are outside KOBANI's direct control."],
  ["How to request a refund", <>Email <a className="text-[#9A7636] underline" href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a> with the booking reference, lead traveller name, reason and supporting information. You may also call <a className="text-[#9A7636] underline" href={`tel:${COMPANY.phones[0]}`}>+233 24 471 9176</a>.</>],
]

const cancellation: Section[] = [
  ["Customer cancellation", "Tell KOBANI promptly if you need to cancel. Cancellation takes effect when acknowledged by KOBANI and is governed by the specific booking terms, supplier commitments, costs already incurred and applicable law."],
  ["Rescheduling", "Requests to change travel dates are subject to availability and supplier approval. Any unavoidable price difference or supplier charge will be explained before a change is confirmed."],
  ["Missed departures and late arrival", "Travellers are responsible for arriving at the confirmed meeting point on time. Contact us immediately if a delay is expected. KOBANI cannot guarantee that a missed service can be recovered, and related costs may not be refundable."],
  ["Cancellation or rescheduling by KOBANI", "KOBANI may cancel or reschedule where safe or proper delivery is not possible. We will contact affected customers using their booking details and explain available alternatives, credits or eligible refunds."],
  ["Itinerary changes and minimum participation", "Reasonable itinerary changes may be necessary for safety, availability or local conditions. A tour may also depend on a communicated minimum participation level. Material changes will be communicated as soon as reasonably possible."],
  ["Accommodation and transport suppliers", "Hotels, carriers, attractions and other independent suppliers may apply their own cancellation and amendment rules. KOBANI will explain relevant supplier restrictions available to us when reviewing a request."],
  ["Extraordinary circumstances", "Severe weather, public-health events, civil unrest, government action, border closures, strikes and similar events outside reasonable control may affect services. We will prioritise safety and provide remedies required by the booking terms and applicable law."],
  ["Refund handling", "Any refund resulting from a cancellation is handled under the KOBANI Refund Policy and the specific booking terms. No general refund percentage applies to every service."],
  ["Contact", <>For help, email <a className="text-[#9A7636] underline" href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a> or call <a className="text-[#9A7636] underline" href={`tel:${COMPANY.phones[0]}`}>+233 24 471 9176</a>.</>],
]

const cookies: Section[] = [
  ["About cookies", "Cookies are small pieces of information stored by a browser. KOBANI uses cookies and similar browser storage only where they support website operation, security and user choices."],
  ["Essential cookies", "Essential cookies help protect authentication, maintain secure sessions, prevent request forgery and support account and checkout functions. Disabling them may prevent parts of the website from working."],
  ["Preferences", "The website may remember choices such as language and cookie consent. Some short-lived booking or navigation information is stored in browser session storage so a selected journey or checkout step can continue."],
  ["Analytics and technical information", "Where website analytics are enabled, proportionate technical information such as page visits, browser or device type, approximate location derived from an IP address and referral information may be processed to understand service performance."],
  ["Payments and third parties", "When you choose to pay, the payment provider may use its own cookies or security technologies on its pages. External social, map and WhatsApp links are governed by the destination service's policies once opened."],
  ["Consent and control", "You can accept or decline non-essential cookies through the website's consent notice where offered. You can also delete or block cookies in your browser. Essential security cookies cannot be disabled through the site while using protected functions."],
  ["Changes and contact", <>We may update this policy when website functionality changes. Questions can be sent to <a className="text-[#9A7636] underline" href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a>.</>],
]

const definitions = {
  privacy: { title: "Privacy Policy", version: LEGAL_VERSIONS.privacy, intro: "This Privacy Policy describes how KOBANI handles personal information under Ghana's Data Protection Act, 2012 (Act 843), while recognising that additional rights may apply in other jurisdictions." },
  terms: { title: "Terms and Conditions", version: LEGAL_VERSIONS.terms, intro: "Please read these Terms carefully before creating an account, making a booking or using KOBANI services." },
  refund: { title: "Refund Policy", version: LEGAL_VERSIONS.refund, intro: "This policy explains how KOBANI considers and processes refund requests without replacing the specific terms supplied for an individual booking or service." },
  cancellation: { title: "Cancellation Policy", version: LEGAL_VERSIONS.cancellation, intro: "This policy explains what happens when a customer, KOBANI or a travel supplier needs to cancel, reschedule or change a service." },
  cookies: { title: "Cookie Policy", version: LEGAL_VERSIONS.cookies, intro: "This policy explains the limited browser storage and cookies used to operate and secure the KOBANI website." },
} as const

export default function LegalPage({ kind, onNavigate }: { kind: LegalKind; onNavigate: (page: Page) => void }) {
  const definition = definitions[kind]
  const sections = kind === "privacy" ? privacy : kind === "terms" ? terms(onNavigate) : kind === "refund" ? refund : kind === "cancellation" ? cancellation : cookies
  return <main id="top" className="min-h-screen bg-[#F8F4EA] text-[#17140F]"><header className="bg-[#0B0B0B] px-5 py-16 text-white"><div className="mx-auto max-w-6xl"><button onClick={() => history.back()} className="mb-8 text-sm text-[#C6A15B]">← Back</button><p className="text-xs uppercase tracking-[.25em] text-[#C6A15B]">Legal information</p><h1 className="mt-3 font-serif text-4xl font-bold sm:text-6xl">{definition.title}</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-white/65">Effective and last updated: {definition.version}. This document applies to KOBANI's website, accounts and related services.</p><button onClick={() => window.print()} className="mt-6 rounded-xl border border-[#C6A15B] px-5 py-2 text-sm text-[#C6A15B] print:hidden">Print document</button></div></header><div className="mx-auto grid max-w-6xl gap-8 px-5 py-10 lg:grid-cols-[240px_1fr]"><nav aria-label="Table of contents" className="h-fit rounded-2xl border border-[#E4DCCF] bg-white p-5 lg:sticky lg:top-5 print:hidden"><b className="font-serif">Contents</b><ol className="mt-4 space-y-2 text-xs">{sections.map((section, index) => <li key={section[0]}><a className="hover:text-[#9A7636]" href={`#section-${index + 1}`}>{index + 1}. {section[0]}</a></li>)}</ol></nav><article className="rounded-2xl border border-[#E4DCCF] bg-white p-6 shadow-sm sm:p-10"><p className="mb-8 leading-7 text-[#625D54]">{definition.intro}</p>{sections.map((section, index) => <section id={`section-${index + 1}`} key={section[0]} className="scroll-mt-6 border-t border-[#EEE7DA] py-7 first:border-0"><p className="text-xs font-bold text-[#C6A15B]">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-1 font-serif text-2xl font-bold">{section[0]}</h2><div className="mt-3 leading-7 text-[#504B43]">{section[1]}</div><a href="#top" className="mt-4 inline-block text-xs font-bold text-[#9A7636] print:hidden">Back to top ↑</a></section>)}<address className="mt-8 rounded-2xl bg-[#0B0B0B] p-6 not-italic text-white"><h2 className="font-serif text-xl font-bold">Contact us</h2><p className="mt-3 text-sm leading-6 text-white/70">{COMPANY.name}<br />{COMPANY.location}<br /><a className="text-[#C6A15B]" href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a><br /><a className="text-[#C6A15B]" href={`tel:${COMPANY.phones[0]}`}>+233 24 471 9176</a></p></address></article></div></main>
}
